### ISSUE TITLE
Compile Errors in Visual Studio 2015

### ISSUE THREAD

**Issue by gorkacortazar** [braitsch/ofxDatGui#1]
In VS 2015 the current version returns 3 compile errors (return missing) in
* bool ofxDatGuiComponent::getIsExpanded() 
* ofxDatGuiHeader* addHeader
* ofxDatGuiFooter* addFooter()

In the first I am returning true in the virtual function and in the other two I am returning the header/footer created or a nullptr, is that ok for you? If so I will submit a PR.

**Comment by braitsch** [comment]
Hi, thanks for reporting this. I just pushed up a fix. ``ofxDatGuiComponent::getIsExpanded()`` eventually needs to be moved into the ofxDatGuiGroup subclass as regular components don't call this method. Adding this to my todos.
