### ISSUE TITLE
missing widgets

### ISSUE THREAD

**Issue by martialgallorini** [braitsch/ofxDatGui#10]
hello,

Very promising Gui, thanks for the hard work and for sharing.

Maybe i am wrong, but i can't see how to : 

- add a simple push button (without toggle)
- make matrix buttons auto exclusive

thanks

**Comment by braitsch** [comment]
You can add a [simple push button](http://braitsch.github.io/ofxDatGui/index.html#basic-buttons) via ```gui->addButton("button label")```

What do you mean by "auto exclusive" in regards to matrix buttons? Radio button type functionality (select one and the rest turn off) is in the [roadmap](https://github.com/braitsch/ofxDatGui/blob/master/roadmap.md) and should be implemented soon.

**Comment by martialgallorini** [comment]
Ok ! i didn't see the push button... that's ok for me.

And yes, auto exclusive is what you described, so great to know it is in the roadmap

thanks again

**Comment by braitsch** [comment]
@martialgallorini 1c6f9343c58a05a7c949d839d58cff02d4b77c14

**Comment by martialgallorini** [comment]
Works perfectly.
thanks a bunch !

Keep up the good work

**Comment by braitsch** [comment]
cool, thanks!
