### ISSUE TITLE
Request: ability to set caps lock off and on

### ISSUE THREAD

**Issue by narner** [braitsch/ofxDatGui#100]
For my app, I'm using the `ofxDatGuiTextInputField` as a way to input values for OSC output messages, specifically hostname and port values. Because a hostname may not be all capital letters, it would be great to have the ability to turn caps lock off and on in `ofxDatGuiTextInputField`. 

Would it be possible to add some sort of parameter letting the caps-lock of the text input field to be toggled off and on? Thanks!

**Comment by mattfelsen** [comment]
Take a look at issue https://github.com/braitsch/ofxDatGui/issues/4. I'm not sure on the specifics of implementing this (I think you subclass `ofxDatGuiTemplate` and set `forceUpperCase` to `false` for `textInput`), but it should be possible.

**Comment by narner** [comment]
Ok, I'll close this issue and take a look at that one.

**Comment by braitsch** [comment]
@narner I just added instance methods that will allow you to set the label of any individual component (or text of a text input) to uppercase.

In your case to toggle the value of a text input between normal and uppercase you can now do: 
````
auto textInput = gui->getTextInput("add message");
textInput->setLabelUpperCase(!textInput->getLabelUpperCase());
````

**Comment by narner** [comment]
@braitsch Brilliant, thank you!

One question - if I'm following you correctly, doing this:
`oscAddressField->setLabelUpperCase(!oscAddressField->getLabelUpperCase());`
 should set my text field to be non-uppercase, correct?

It looks as if the text field's `mUpperCase` property is still set to `true`:

![screen shot 2016-10-02 at 11 07 04 am](https://cloud.githubusercontent.com/assets/2131591/19021496/0ef3f236-8891-11e6-8bee-58aa66a51681.png)

**Comment by narner** [comment]
Gotchya. I tried setting 
`oscAddressField->setLabelUpperCase(false);`, but for some reason the `mUpperCaseProperty` is still set to `true`: 

![screen shot 2016-10-02 at 12 38 26 pm](https://cloud.githubusercontent.com/assets/2131591/19022075/621f8b30-889d-11e6-8c69-23c3b68ead4e.png)

Thanks for your time / patience / sorry if I'm missing something obvious!

**Comment by braitsch** [comment]
``mUpperCaseText`` applies to the text of the text input, not the label. To set the label to uppercase use ``setLabelUpperCase(true)`` to set the text of a text input to uppercase use ``setTextUpperCase(true)``.
