### ISSUE TITLE
Problem with state of toggle buttons

### ISSUE THREAD

**Issue by narner** [braitsch/ofxDatGui#101]
I'm working on implementing instances of `ofxDatGuiToggle`, as demonstrated in the [example-Buttons project](https://github.com/braitsch/ofxDatGui/tree/master/example-Buttons).

Following the pattern in the example project, I declare my two buttons in `ofApp.h`:

```
        ofxDatGuiButton *receiveOsc;
        ofxDatGuiButton *sendOsc;

```

Then, in `ofApp.cpp`, I have a method `setupToggles` method to create and position these toggles:

```
void ofApp::setupToggles(){
    receiveOsc = new ofxDatGuiToggle("RECEIVE OSC", false);
    sendOsc = new ofxDatGuiToggle("SEND OSC", false);
    
    receiveOsc->onButtonEvent(this, &ofApp::onButtonEvent);
    sendOsc->onButtonEvent(this, &ofApp::onButtonEvent);
    
    receiveOsc->setPosition(ofGetWidth()/1.3 - receiveOsc->getWidth()/2, 60);
    sendOsc->setPosition(ofGetWidth()/1.3 - sendOsc->getWidth()/2, 100);
}
```

I also made sure to draw these in the `draw()` method:
```
    receiveOsc->draw();
    sendOsc->draw();

```

As well as add the calls to `update` in the `update()` method:

```
receiveOsc->update();
sendOsc->update();

```

However, for some reason in my app there is a square where the circle is in the example-Buttons project. Additionally, the button doesn't seem to register the toggle state.

I made a [screen-cast video](https://www.youtube.com/watch?v=Hcp33w6FjNU) to show exactly what I mean.

**Comment by mattfelsen** [comment]
Hey @narner. Regarding the white squares, my guess is the images for the checked & unchecked states aren't being loaded, so you're getting a blank/white texture instead of an image of a circle. In the console, do you see any messages that say any images failed to load and/or drawing an unallocated texture? If you haven't copied the `ofxbraitsch` folder from the addon into your app's `bin/data` folder, that's probably the cause.

For the buttons not working...are you using the latest version of ofxDatGui? I know at some point fairly recently things changed and you need to use `ofxDatGuiToggleEvent` instead of `ofxDatGuiButtonEvent` for toggles. It looks like the in the button example is actually out of date (and I'm surprised it works in your screencast), but take a look at `example-AllComponents`.

Hope that helps!

**Comment by narner** [comment]
Hey @mattfelsen, thanks for your response. I hadn't had included `ofxBraitsch` in my app's `bin/data` folder, so that may be part of the problem. 

It looks like I didn't have the latest version of `ofxDatGui`. I have the latest version now, but I'm now experiencing a different problem. After downloading the newest version and including it in my project, I'm getting a build error in `ofxDatGuiIntObject.h` at line 90 stating "No viable overloaded'='".

**Comment by mattfelsen** [comment]
I just tried the latest ofxDatGui with OF 0.9.3, and both `example-AllComponents` and `example-AllComponentsGui` work fine. Are you sure the problem isn't with your app's code? It's possible that the files in ofxDatGui have changed, so you could try using the OF projectGenerator to update/recreate your project.

**Comment by narner** [comment]
@mattfelsen Yup, the problem was with my code, my bad. That's fixed now. One last question (sorry, new to OF). I copied the `ofxbraitsch` into my app's `bin/data` folder like so:

![screen shot 2016-09-24 at 4 37 58 pm](https://cloud.githubusercontent.com/assets/2131591/18811130/52b7ce7e-8275-11e6-9086-a835df3123b3.png)

but I'm getting the error logs below:

```
[ error ] ofImage: loadImage(): couldn't load image from "ofxbraitsch/ofxdatgui/icon-group-open.png"
[ error ] ofImage: loadImage(): couldn't load image from "ofxbraitsch/ofxdatgui/icon-group-closed.png"

```

What else do I need to do besides copying the folder to have those assets properly load? 
Thanks again for your time!

**Comment by mattfelsen** [comment]
Hm, that is strange! You've got it in the right place. Silly question, but are you sure those files exist inside the `bin/data/ofxbraitsch/ofxdatgui` folder? And are they valid files (i.e. you can view them in the Finder/Preview?)

**Comment by narner** [comment]
Hmmm yeah, this is what the folder contents look like (I can open them all in finder/preview):
![screen shot 2016-09-24 at 4 58 29 pm](https://cloud.githubusercontent.com/assets/2131591/18811251/2360860e-8278-11e6-9735-b0f7ded1308f.png)

**Comment by mattfelsen** [comment]
Well those files look fine, but it's complaining about icon-group-open.png & icon-group-closed.png – they're not in that folder!!

**Comment by narner** [comment]
Ah shoot my bad :| 
Added them in now...
In any rate, I'm still experiencing the problem of the toggle buttons not displaying the proper images:
![screen shot 2016-09-24 at 5 03 51 pm](https://cloud.githubusercontent.com/assets/2131591/18811308/d3581cb0-8279-11e6-9e19-24908d0cc916.png)

**Comment by mattfelsen** [comment]
Ah right, funky. It looks like the dropdown icon is actually displaying
incorrectly too. Since the example works, there's probably something in
your app that is changing a drawing or graphics state.


Are you doing anything in your app relating to thinks like
enabling/disabling ARB textures, leaving depth test on, leaving lighting
enabled, etc? It's probably something like that...you could try commenting
out everything in `ofApp::draw()` to see if it draws properly then, and
then add things back in little by little to find the culprit.

**Comment by narner** [comment]
Yup, that was definitely the problem; thank you. 

For reference, this was the problem code:

```
void ofApp::draw(){
    
    float margin = 10;
    magnitudePlot.draw( margin, 260, ofGetWidth() - margin * 2, 480 );
    
    oscInputPortField->draw();
    oscOutputHostNameField->draw();
    oscOutputPortField->draw();
    oscAddressField->draw();
    oscMessagePayloadSelector->draw();
    
    receiveOsc->draw();
    sendOsc->draw();
}
```

The first two lines in the draw method are for displaying an instance of this [time-series plot](https://github.com/nickgillian/ofxGrt/blob/c8dd4e872107fabfbc643b12b650236c3af7986a/src/ofxGrtTimeseriesPlot.cpp). If I comment those two lines out, then the `ofxDatGuiToggle` buttons display and work properly. 

I'll go ahead and close this issue, but if anyone has any insights, I'd definitely welcome them!

**Comment by mattfelsen** [comment]
You could try wrapping the draw call to the plot in `ofPushStyle()` and `ofPopStyle()`?

**Comment by narner** [comment]
Ah, wasn't actually aware of those methods...do you mean like this? 

```
void ofApp::pushStyle(){
    float margin = 10;
    magnitudePlot.draw( margin, 260, ofGetWidth() - margin * 2, 200 );
}

void ofApp::popStyle(){
    float margin = 10;
    magnitudePlot.draw( margin, 260, ofGetWidth() - margin * 2, 200 );
}
```

Doing that doesn't seem to draw the plot at all for some reason (?)

**Comment by mattfelsen** [comment]
Sorry no, I meant like this:

```
void ofApp::draw(){

    ofPushStyle();
    float margin = 10;
    magnitudePlot.draw( margin, 260, ofGetWidth() - margin * 2, 480 );
    ofPopStyle();

    oscInputPortField->draw();
    oscOutputHostNameField->draw();
    oscOutputPortField->draw();
    oscAddressField->draw();
    oscMessagePayloadSelector->draw();

    receiveOsc->draw();
    sendOsc->draw();
}
```

**Comment by narner** [comment]
Ha, perfect, thank you so much!
