### ISSUE TITLE
Increase gui text size

### ISSUE THREAD

**Issue by VVZen** [braitsch/ofxDatGui#103]
Not really a serious issue, but after testing on my 2k monitor the size of the text used in the gui is quite tiny.
If there was a way to increase it by just a few points, readability would be much better.
It is something that I can adjust editing to the **SmartFont** class?
Thanks

**Comment by braitsch** [comment]
You can set the font and its size in the [theme that styles your gui](https://github.com/braitsch/ofxDatGui/blob/master/src/themes/ofxDatGuiTheme.h#L224).
````
class myCustomTheme : public ofxDatGuiTheme{
    public:
        myCustomTheme(){
            font.size = 10;
            font.file = "path/to/font.ttf";
            init();
        }
}
````

**Comment by VVZen** [comment]
Wow thank you. 
That what a _really_ quick answer!
Great work on the library, and thank you so much!

**Comment by braitsch** [comment]
You're welcome, glad you're finding it helpful!
