### ISSUE TITLE
ofxDatGuiSlider::dispatchEvent() doesn't update bounded variable

### ISSUE THREAD

**Issue by avilleret** [braitsch/ofxDatGui#106]
bounded variables are updated with `dispatchSliderChangedEvent()` which call `dispatchEvent()` itself
since `dispatchSliderChangedEvent()` is private, we can't update bounded variable when using `setValue()`

**Comment by avilleret** [comment]
this will be fixed with https://github.com/braitsch/ofxDatGui/pull/98/commits/699f538e6e2fe8f96383e1774eb86d5719461079

**Comment by bafonso** [comment]
This is also broken for dropdownmenus

**Comment by avilleret** [comment]
@bafonso see my [dev](https://github.com/avilleret/ofxDatGui/tree/dev) branch where lots of issues have been fixed
