### ISSUE TITLE
click to expand color pickers

### ISSUE THREAD

**Issue by martialgallorini** [braitsch/ofxDatGui#11]
hello,

is it possible to force mouse click to open a color picker instead of auto expanding it on mouse hover ?

this can lead to problems when using two consecutive color pickers

thanks

**Comment by braitsch** [comment]
Hi, how would it lead to problems? If you have two consecutive color pickers the one below will not receive events if the one above it is active.

**Comment by martialgallorini** [comment]
Well it doesn't really lead to bugs but can get a bit messy. See the generativeLines example : 

<img width="521" alt="capture d ecran 2015-10-16 a 00 21 06" src="https://cloud.githubusercontent.com/assets/3931994/10529212/2ab8dad2-739c-11e5-84d2-27b3751d9dee.png">

**Comment by braitsch** [comment]
This is a bug, each picker should close when it loses focus.

**Comment by martialgallorini** [comment]
i think they don't loose focus unless the mouse is out of the entire widget area (expanded color palette included)

it would be nice to have color choosers expandable by click though

**Comment by braitsch** [comment]
Color pickers now correctly lose focus on mouseleave unless the input field is active in which case the picker loses focus when either another component gains focus or a mousepress is dectected outside of the picker. 6f13e581415dc2ec56474b55b2830957336cb9ba

**Comment by martialgallorini** [comment]
yes this looks great now. Thanks.
