### ISSUE TITLE
can't work with ofEnableDepthTest() 

### ISSUE THREAD

**Issue by ryanaltair** [braitsch/ofxDatGui#111]
help!
when use `ofEnableDepthTest();`
the ofxDatGui can't work well, the font and other shape just disappear;
when `ofEnableDepthTest()` is not used;
everything goes well;

I try the master branch and dev branch both, same output.

see below the framerate monitor is disappear;
//use `ofEnableDepthTest();` 
<img width="755" alt="ofenabledepthtest within" src="https://cloud.githubusercontent.com/assets/2869522/20785976/2f138ed8-b7de-11e6-8a14-292f4a3b00b1.png">

//not use `ofEnableDepthTest(); `
<img width="675" alt="ofenabledepthtest without" src="https://cloud.githubusercontent.com/assets/2869522/20785995/50ded3b0-b7de-11e6-9ddd-7bb4839ff3df.png">

thank you!

**Comment by mattfelsen** [comment]
Hi @ryanaltair. Try adding `ofDisableDepthTest()` at the end of your `draw()` method. That will turn depth test off by the time ofxDatGui begins drawing your components.

**Comment by ryanaltair** [comment]
it is great! Work now.
