### ISSUE TITLE
ofxDatGuiDropdown area not redrawing on click event

### ISSUE THREAD

**Issue by autr** [braitsch/ofxDatGui#112]
Dropdown element closes if the header is clicked, but not if a dropdown item is clicked - a blank area stays open and the icon is not updated to the new state. 

I've tried manually setting mHeight and mIsExpanded on the DropdownEvent, then running ofxDatGui->update(), but no luck...

**Comment by braitsch** [comment]
Hi there, the dropdown menu example works fine on both osx and windows in v0.9.8. Feel free to post steps to reproduce what you are seeing.
