### ISSUE TITLE
Text size Problems with surface pro and resolutions of screen

### ISSUE THREAD

**Issue by ChristophGuillermet** [braitsch/ofxDatGui#117]
Hello.

on surface pro 4 i have a beautifull GUI with a good text writting on screen. But if i change the resolution of the screen or try it on another laptop, the GUI Text is un readable at all.

is there any way to resize the GUI (boxes and TEXT from screen dimensions) ? any function already doing it ?

![normal](https://cloud.githubusercontent.com/assets/5006744/22584160/2ca6597e-e9f1-11e6-87a1-031cf412d230.jpg)
![bad](https://cloud.githubusercontent.com/assets/5006744/22584162/2e6c1910-e9f1-11e6-871e-c6f742e9e540.jpg)

thanks

**Comment by braitsch** [comment]
High resolution mode is triggered if the display resolution is >= 2560x1600px. You can change to match the resolution of your display in [ofxDatGuiTheme](https://github.com/braitsch/ofxDatGui/blob/master/src/themes/ofxDatGuiTheme.h#L27).

**Comment by ChristophGuillermet** [comment]
Hum.... its very strange. its like the resolution is not complete during the resizing of the GUI elements. 
i have already tried to change the resolution of retina but without any change in the result.

if i change my resolution of screen, all texts and proportions are ok and readable with OF, but not with the ofxDatGui part.

**Comment by braitsch** [comment]
Have you tried restarting the app after changing the resolution? ofxDatGui only inspects the screen resolution when the app is first launched, any changes to the resolution while the app is running are currently ignored.

**Comment by ChristophGuillermet** [comment]
yes, of course.
i was thinking it could be a W10 trouble but also after restart, or just putting the app on another laptop with standard (1368x768) resolution, its the same thing: fonts are not drawn correctly

**Comment by sam-mcelhinney** [comment]
hello,
I'm just get started with the library, but have a similar text resolution problem. If I start my app with the below, it has pixelated text. If I remove &window settings then I don't have the issue, text looks lovely and crisp, but I do need this setting for elsewhere... Is there any workaround where I can solve this?

Ta,
S

`    ofAppGlutWindow window;
    window.setGlutDisplayString("rgba double depth alpha samples>=24");
    ofSetupOpenGL(&window, 1280, 800, OF_FULLSCREEN);
    ofSetFrameRate(60);
    ofSetVerticalSync(false);
	ofRunApp(new ofApp());`

**Comment by braitsch** [comment]
ce0a38f9a5a6aba57d60939d2dac94e980dad200 on the dev branch now uses ``getPixelScreenCoordScale()`` to detect a high resolution display instead of hardcoded pixel values. Can you confirm if this resolves your issue?

**Comment by sam-mcelhinney** [comment]
Hi, sorry to reopen this, but I still have issues with text being pixelated when not running in HD mode; both on Mac and PC. 

It isn’t such an issue in Mac, as the default setting is now usually retina, which triggers high res and nice crisp fonts. But, on PC the underlying pixel coord ratio is often 1, so the high resolution mode isn’t triggered, and users often complain that the menu text isn’t very visible.

Is there any way round this?
