### ISSUE TITLE
overloading values from components without  oF Parameters

### ISSUE THREAD

**Issue by ChristophGuillermet** [braitsch/ofxDatGui#118]
I m using the GUI to setup element picked up with mouse. 

i would like to refresh the GUI when an element is selected, to have its values : text, values, color

is there any way to achieve this easely without using oFParameters ? (the example is quite not really clear for a first approach)

thanks

**Comment by braitsch** [comment]
Take a look at the [data binding example](https://github.com/braitsch/ofxDatGui/blob/master/example-DataBinding/src/ofApp.cpp). This will show you how to update a component based on an external event, e.g. mouse moved, clicked etc..

**Comment by ChristophGuillermet** [comment]
thanks a lot. :)
i m having some trouble with the binding function:

`sliderFaderSizeX->bind( myFaders[_fader].getSizeX() );
`
or trying to do:
```
	double _tmp = myFaders[_fader].getSizeX();
	sliderFaderSizeX->bind(_tmp);
```
where 

```
int wcFader::getSizeX()
{
	return(sizeX);
}
```
I presume this is just a simple thing, but im not seeing how to pass the value to the bind function.

I have also another question: how can i create a slider with INT type ?

Voilà ! et merci

**Comment by mattfelsen** [comment]
Hey @ChristophGuillermet, I think you may have luck if you pass a reference (rather than a value) to the `bind()` method. Try changing your `wcFader::getSizeX()` metho to return an `int&` instead of `int` and then you should be able to use the `sliderFaderSizeX->bind( myFaders[_fader].getSizeX() );` line. Alternatively, you could make the `sizeX` member public and just access it directly if that works for you.

**Comment by ChristophGuillermet** [comment]
hello @mattfelsen mattfelsen :) 
thank you !
can you just show me the principle of this way of such a function ?

something like this ?

```
int wcFader::getSizeX()
{
        int& _ref= sizeX;
	return(_ref);
}
```

**Comment by mattfelsen** [comment]
Sure, you'll need to change your method signature, but the definition can stay the same.

In your header file, change
`int wcFader::getSizeX();`
to
`int& wcFader::getSizeX();`


In your implementation file, change
```
int wcFader::getSizeX()
{
	return(sizeX);
}
```
to
```
int& wcFader::getSizeX()
{
	return(sizeX);
}
```

Also, I haven't seen/used the `return(variable);` syntax – I usually use `return variable;` but if it works for you, then cool.

**Comment by ChristophGuillermet** [comment]
ah yes ! great !!!!

some other questions around the binding: 

- how can i set this slider being **INT** type  ? I dont want to have a floating point value

- is there any object like a kind of ofxDatGuiAddValue (int or float) to have some parameters ? ( i m using actually text input with ofStringToInt() function )
cheers

**Comment by mattfelsen** [comment]
You can use `mySlider->setPrecision(0);` to make the slider appear as an int slider with no decimal places. If you use `mySlider->getValue();` I think it will still return a float, but you can assign to/cast to an int without an issue.

I'm not sure what you're asking about the AddValue. Can you try rephrasing or giving an example/some pseudo code to explain what you're trying to do?

**Comment by ChristophGuillermet** [comment]
:)

for the moment in setup i m doing
`faderMenu->addTextInput("Number", "");
`
and when event is seen as text for "Number", i convert the string in int.

i would like to have something like:
```

ofxDatGuiValue* valueNumber;

valueNumber= faderMenu->addValueInt("Number");

valueNumber->bind(myFaders[_fader].getNumber());

```

**Comment by mattfelsen** [comment]
If you use slider components, there is both a draggable slider area and an area on the right for text input of the number. If you only want the text input without the slider, you're already going about it the right way by using the text input component and converting a `string` to an `int`. I don't see much benefit to what you're suggesting (or perhaps I'm still not understanding correctly).

Also, I should add, I'm not the author of the addon, just trying to offer some help 🙂

**Comment by ChristophGuillermet** [comment]
well you are very helpfull and it was just perfect :)
thank you

**Comment by ChristophGuillermet** [comment]
hum color binding doesnt seems to be possible in ofxDatGui. what would the best approach for you ?

**Comment by mattfelsen** [comment]
That's correct, it's only implemented for sliders. For now you can use the same approach as when a text input gets updated: detect it in the callback and access the value from the component.
https://braitsch.github.io/ofxDatGui/index.html#events

**Comment by ChristophGuillermet** [comment]
yep, but still same problem, i cant refresh the color of the Gui from an element having an ofColor.... have you any idea on how to create such a function by modifying the ofxDatGui library ?

**Comment by mattfelsen** [comment]
Sure you can, there are multiple ways:
https://github.com/braitsch/ofxDatGui/blob/0695cc276eb5617c5e37deac5a323ca3110a5ff7/src/components/ofxDatGuiColorPicker.h#L74-L90

**Comment by ChristophGuillermet** [comment]
Marvelous !!! i was completely lost searching inside the lib ;)
thanks a lot
