### ISSUE TITLE
Text input not correctly formated

### ISSUE THREAD

**Issue by ChristophGuillermet** [braitsch/ofxDatGui#119]
Text input caracters are shown in Uppercase, but the real input is Lowercase. How to have the input shown in the GUI in Lowercase ?

ah... euh... i m french, accents are really missing

merci

**Comment by ChristophGuillermet** [comment]
ok founded in ofxDatGuiTheme 
`struct {
        
        // general rules that are shared by all components //
            float width = 270.0f;
            float height = 26.0f;
            float padding = 2.0f;
            float vMargin = 1.0f; // vertical spacing between gui components //
            float iconSize = 12.0f;
            float labelWidth = 95.0f;
            float labelMargin = 12.0f;
            float breakHeight = 3.0f;
            **bool upperCaseLabels = true;`**

**Comment by ChristophGuillermet** [comment]
how can we modify the source to accept accents from french language ? é à etc....

**Comment by braitsch** [comment]
You don't have to modify the source, just use a font that supports the character set you want. You can set the font within [ofxDatGuiTheme](https://github.com/braitsch/ofxDatGui/blob/master/src/themes/ofxDatGuiTheme.h#L225).

**Comment by ChristophGuillermet** [comment]
hello braistch and thank you for your answer !

the fonts used are correct on my laptop, taking the accents in other apps. 
its not the font it seems to be the scan of the keyboard combination wich doent allows special french accent as input  (é è ê â à û ù ï î and  €, and  apostrophes " or '  )

**Comment by braitsch** [comment]
Hmm, it may be a limitation of [ofTrueTypeFont](http://openframeworks.cc/documentation/graphics/ofTrueTypeFont/) then. Can you confirm that your font file displays correctly when using it in a normal ofTrueTypeFont instance?

**Comment by ChristophGuillermet** [comment]
Thank you braitsch, it seems to be something no more working in of about fullset character initialisation:

bool ofTrueTypeFont::load(const string &filename, int fontsize, bool _bAntiAliased=true, bool _bFullCharacterSet=true, bool makeContours=false, float simplifyAmt=0.3f, int dpi=0)

i will post on OF forum so ....
