### ISSUE TITLE
widgets resolution

### ISSUE THREAD

**Issue by martialgallorini** [braitsch/ofxDatGui#12]
hello,

i am facing a problem : when i build an example, widgets are small sized with a good resolution.

<img width="759" alt="capture d ecran 2015-10-16 a 10 49 35" src="https://cloud.githubusercontent.com/assets/3931994/10537837/cc87e62a-73f4-11e5-8c99-37c32b6ca143.png">

i have created a new project using project generator and i can't have the same result, my widgets seem oversized.

<img width="1094" alt="capture d ecran 2015-10-16 a 10 50 24" src="https://cloud.githubusercontent.com/assets/3931994/10537844/d2309b30-73f4-11e5-8776-f0a8a3cf7f91.png">

I copied the example code into my project, same issue...

is there a special xcode configuration ?

PS : using XCode 4.6.1 under yosemite with yesterday's OF nightly

**Comment by braitsch** [comment]
The project generator doesn't automatically enable high resolution capabilities but this is an easy fix within openFrameworks-Info.plist. Click the "+"  to add a new row and add the following entry:

<img width="837" alt="screen shot 2015-10-16 at 8 49 18 am" src="https://cloud.githubusercontent.com/assets/144289/10546527/4e443126-73e3-11e5-9628-4e07e655587e.png">

**Comment by martialgallorini** [comment]
ok thank you, that did the trick.
By the way, does it mean the problem will happen for every screen considered "non high resolution" ?

**Comment by braitsch** [comment]
You should still query the window dimensions via ofGetWidth/Height or something similar and size your application appropriately.
