### ISSUE TITLE
The GUI is always drawn on top of everything

### ISSUE THREAD

**Issue by razvanilin** [braitsch/ofxDatGui#121]
I'm trying to make the `gui` to be drawn under one of my layers and I can't seem to be able to achieve this.

The problem is shown below where the slider should appear under the browser interface:

<img width="534" alt="capture" src="https://cloud.githubusercontent.com/assets/5342321/22976046/f8841214-f380-11e6-9a28-70fe47ac8b1d.PNG">

In my main `draw()` loop I have the following:

```
ofApp::draw() {

    //....
    // draw the video player only if it's necessary
    if (browser.IsVideoPlayerStarted() && VideoPlayer::isStarted)
        videoPlayer.draw();
    
    ofSetColor(255);
    browser.draw(0, 0);
}
```

The video player has its own video player controls where the ofxDatGui comes into place

The `VideoPlayer` draw loop looks like this:

```
void VideoPlayer::draw(int x, int y) {
    if (VideoPlayer::isStarted && _videoPlayer->isLoaded()) {
        _x = x; _y = y;
        _videoPlayer->draw(x, y, _width, _height);
        _controls->draw(x, y);
    }
    
}
```

The Video Player is drawn before the browser correctly, but the controls are not and they always appear above everything else.

The setup and draw for the controls:

```
void VideoPlayerControls::setup(ofVideoPlayer* videoPlayer) {
    this->videoPlayer = videoPlayer;
    _isHovered = false;
    _playButton.load("buttons/play/play.png");
    _backwardButton.load("buttons/backward/backward.png");
    _forwardButton.load("buttons/forward/forward.png");

    gui = new ofxDatGui(0, 0);
	gui->setAssetPath("./");
    slider = gui->addSlider("Video Slider", 0, videoPlayer->getDuration());
    
    gui->onSliderEvent(this, &VideoPlayerControls::onSliderEvent);
    gui->setVisible(false);
}

void VideoPlayerControls::draw(int x, int y) {
    //gui->setPosition(x - (_width/2), y - _height + 20);
	
    if (_isHovered) {
        _playX = x + (_width/2) - (_playButton.getWidth()/2);
        _playY = y + (_height/2) - (_playButton.getHeight()/2);
        _playButton.draw(_playX, _playY);
        
        _backwardX = x + (_width/2) - (_playButton.getWidth()*2);
        _backwardY = y + (_height/2) - (_playButton.getHeight()/2);
        _backwardButton.draw(_backwardX, _backwardY);
        
        _forwardX = x + (_width/2) + (_playButton.getWidth());
        _forwardY = y + (_height/2) - (_playButton.getHeight()/2);
        _forwardButton.draw(_forwardX, _forwardY);
    }
}
```

Am I missing something obvious here, or is this addon meant to act like that?
Cheers!

**Comment by mattfelsen** [comment]
Hey @razvanilin, it's probably the autodraw the is messing you up. By default, ofxDatGui is set up with autodraw on, meaning you don't have to call `update()` or `draw()` on the `gui` objects since it happens automatically after `ofApp::update()` and `ofApp::draw()` get called. Instead, you can turn that off with `myGui->setAutoDraw(false);` and then manually update & draw the gui yourself at whichever point in your code works.

https://braitsch.github.io/ofxDatGui/index.html#auto-rendering

**Comment by razvanilin** [comment]
Just tried that and it works! Thanks a lot
