### ISSUE TITLE
Bottom anchors are not resizing

### ISSUE THREAD

**Issue by hugohil** [braitsch/ofxDatGui#122]
I think this GIF might be more explicit:

![ofxdatgui-bottom-position](https://cloud.githubusercontent.com/assets/4352715/24216368/3c3b7ad4-0f3c-11e7-9a7e-44b143f3dcfc.gif)

* oF `0.9.3`
* macOS `10.12.2`

**Comment by hugohil** [comment]
I managed to have it working but I still have an issue with dropdown, as the resizing seems to be called only when the dropdown is closed:

![ofxdatgui-bottom-dropdown](https://cloud.githubusercontent.com/assets/4352715/24218433/a24a9a24-0f43-11e7-9297-b3d016ebc0ea.gif)

**Comment by BenBergman** [comment]
I am having the same problem with my GUI docked in the top left. If I click the arrow to close the dropdown, it resizes correctly. If I select an entry from the dropdown, the dropdown closes but the GUI space allocation is still retained.

**Comment by braitsch** [comment]
This should now be fixed on the dev branch which will soon be merged into master.
