### ISSUE TITLE
New elements: any use?

### ISSUE THREAD

**Issue by DanBennettDev** [braitsch/ofxDatGui#124]
Hi,
Not sure on the etiquette here as I've not contributed to anyone else's repo before, but I extended ofxDatGui a bit for a project I was working on - a piano keyboard element, and an adaptation of the matrix to allow for text labels. I'm a little way behind this branch now, but if either feature is of interest for inclusion I'll bring my branch up to date and then do whatever else is required.

Cheers
Dan

**Comment by braitsch** [comment]
Go ahead and submit a pull request and I'll take a look. The dev branch is several commits ahead of master so please pull the latest from there.
