### ISSUE TITLE
the theme ofxDatGuiThemeCharcoal doesn't shows the addBreak spaces

### ISSUE THREAD

**Issue by moebiussurfing** [braitsch/ofxDatGui#125]
Hello, when I swap to that theme with: 
`sensors_gui->setTheme(new ofxDatGuiThemeCharcoal);`

then the gui doesn't show the vertical spacing between gui objects. It shows like if the addBreak was not added...
`sensors_gui->addBreak()->setHeight(40.0f);`

is this a normal thing because how this theme is build?

i am in 0.9.8, vs 2015 w10. thanks for the addon!!

**Comment by braitsch** [comment]
You can set the desired default vertical spacing between components in the theme. When a theme is applied it overwrites any instance variables you set on the components or whatever settings were applied by the previous theme. To set the vertical spacing add ``layout.breakHeight = 40.0f;`` to the [constructor of the theme](https://github.com/braitsch/ofxDatGui/blob/master/src/themes/ofxDatGuiThemes.h#L36).
