### ISSUE TITLE
Support for RPI/Linux ARM 

### ISSUE THREAD

**Issue by ImanolGo** [braitsch/ofxDatGui#134]
Hi,
I recently did a fresh install of OpenFrameworks v0.9.8 on my Raspberry Pi3 with Jessie OS and the latest version of ofxDatGui.

However, I get a bunch of errors like,

```
ofxDatGuiTimeGraph.h:89:53: error: ‘glPolygonMode’ was not declared in this scope
             glPolygonMode(GL_FRONT_AND_BACK, GL_FILL);
```

Do you know what it could be?

**Comment by braitsch** [comment]
RPI/linux arm is not currently supported.

**Comment by RuolunWeng** [comment]
hi,

Rpi/linux arm is STILL not  supported ??

**Comment by braitsch** [comment]
@RuolunWeng Have you forked the repo, added support for RPI/Linux and submitted a pull request? When then it appears that RPI/Linux is still not supported.
