### ISSUE TITLE
GUI and OfLights

### ISSUE THREAD

**Issue by cyrstem** [braitsch/ofxDatGui#138]
hi  having an issue  with ofxDatGui  when working with 3dLights
 on openframework s the gui gets opaque theres a way to fix this ?

**Comment by mattfelsen** [comment]
Hi @cyrstem. I've used this addon with a 3d scene with lighting. Are you calling `light.disable()` and/or `ofDisableLighting()` before drawing the gui?

**Comment by cyrstem** [comment]
hi, im using 
    luz.enable();
    ofEnableAlphaBlending();
    ofEnableDepthTest();
 and  ending 
 //---------Light-----------------
    luz.disable();
    ofDisableAlphaBlending();
    ofDisableDepthTest();
but  i dont call gui->draw() at any time

**Comment by mattfelsen** [comment]
Try calling `ofEnableLighting()` at the beginning of your draw method, and `ofDisableLighting()` at the end of your draw method to see if that does the trick. (The gui is automatically drawn after your `ofApp::draw()` method if you leave autodraw enabled, which is the default)

**Comment by cyrstem** [comment]
thanks! that works!!
