### ISSUE TITLE
how to draw a line above the plot graph?

### ISSUE THREAD

**Issue by moebiussurfing** [braitsch/ofxDatGui#139]
I am trying this, but the gui always draws in the front... any idea?

**Comment by braitsch** [comment]
By default, ofxDatGui draws itself above everything else in your application. You can disable this behavior with ``gui->setAutoDraw(false)`` which will then require you to call ``gui->draw()`` manually inside of your application's draw loop. This will allow you to draw your line after you call ``gui->draw()``.
