### ISSUE TITLE
Widgets loose focus while dragging mouse

### ISSUE THREAD

**Issue by martialgallorini** [braitsch/ofxDatGui#14]
Widgets should keep focus when clicked and dragged until mouse release.

example : add 2 buttons and 2 sliders

click the first button and keep mouse pressed.
Drag left or right -> ok
Drag bottom -> widgets get focus and activates when mouse hover

**Comment by braitsch** [comment]
Not entirely sure I understand this. Widgets do lose focus when the mouse leaves the component while pressed however if the mouse moves onto an adjacent component (while it is pressed) then that component will capture focus and take input. That is the desired behavior.

**Comment by martialgallorini** [comment]
I don't remember seeing this kind of behavior before.
When the mouse hovers widgets, widget get focus, that is ok.
But when i drag a control, for example a slider, if the mouse goes outside the slider, this should keep controlling this slider, not the one above that gets the new focus.

This leads to usable issues

**Comment by braitsch** [comment]
I see what you mean. Currently components lose focus when the mouse is dragged off of it instead of when another component steals it away. I'll take a look at altering this behavior.

**Comment by braitsch** [comment]
@martialgallorini 6f13e581415dc2ec56474b55b2830957336cb9ba

**Comment by martialgallorini** [comment]
yes this is better, but not entirely.
strangely, it seems to be ok when dragging downwards... but not when dragging upwards...

**Comment by martialgallorini** [comment]
isn't there a bug left ?
