### ISSUE TITLE
Button size

### ISSUE THREAD

**Issue by houyuan2** [braitsch/ofxDatGui#143]
Is it possible to set the height of a ofxDatGuiButton*? I only find setWidth() but no setHeight()

**Comment by braitsch** [comment]
The height of each component, as well as other layout values, is hardcoded in [ofxDatGuiTheme](https://github.com/braitsch/ofxDatGui/blob/master/src/themes/ofxDatGuiTheme.h#L177). You can override any of these values by [creating a custom theme](https://github.com/braitsch/ofxDatGui/blob/master/src/themes/ofxDatGuiThemes.h), which extends ofxDatGuiTheme, and applying that to your gui.
