### ISSUE TITLE
std namespace is assumed and causes compile error with latest release build: ofx 0.10.0 

### ISSUE THREAD

**Issue by braedenf** [braitsch/ofxDatGui#144]
The library doesn't compile, the ofxSmartFont.h file assumes that the namespace of std is declared in the openframeworks library. However the latest release build only includes std in ofMain.
I fixed the issue just by adding `using namespace std` at the top of the file. 

Was discussed on the forum: https://forum.openframeworks.cc/t/ofxdatgui-compilation-errors-on-windows-visual-studio-2015/29509/3

**Comment by braitsch** [comment]
Thanks. I just recreated the example project files and updated ofxSmartFont to support oF v0.10.0 & Xcode 9.4. The updates are on the dev branch but will be merged into master in the next few days.
