### ISSUE TITLE
scrollView move and remove clear entire scrollview

### ISSUE THREAD

**Issue by CptOrange16** [braitsch/ofxDatGui#146]
Hello
I've been experimenting with the scrollview and I'm trying to remove a single element on the click of a button:
myScrollView->remove(selectedIndex);
and also move a single element from a certain index to another:
```
if (e.target == moveButton) {
		int index = 0;
		myScrollView->move(selectedIndex, index);
}
```
Whenever I use any of those methods, after updating the scrollview just clears.
Do you have any idea on what may be causing this problem?
Thanks
(if you need any more information let me know i'll update this)

**Comment by braitsch** [comment]
Hi, both the move and remove functions appear to be working as expected. Does the [ScrollViewExample](https://github.com/braitsch/ofxDatGui/tree/master/example-ScrollView) project reproduce the behavior you're experiencing?
