### ISSUE TITLE
Set GUI Panel non draggable

### ISSUE THREAD

**Issue by martialgallorini** [braitsch/ofxDatGui#15]
hello,

it would be nice to be able to set gui panel non draggable to fix its position.
useful when designing simple standalone gui interfaces.

**Comment by braitsch** [comment]
Good point. I'll take a look at adding this.

**Comment by braitsch** [comment]
5b7abb692f3b8afdaca21f46a725dacc1b656bce

**Comment by martialgallorini** [comment]
Hello,

Unless i am the problem, this doesn't seem to work for me...

thanks
