### ISSUE TITLE
ofVec2f support for slider

### ISSUE THREAD

**Issue by baydam** [braitsch/ofxDatGui#151]

**Comment by mattfelsen** [comment]
Hey @baydam. I'm not sure exactly what you're trying to do, but you can currently create two sliders, and bind one to your variable's x value and one to the y value. Something like...

```
ofVec2f position;
gui->addSlider("Position x", 0, 1)->bind(position.x);
gui->addSlider("Position y", 0, 1)->bind(position.y);
```

**Comment by baydam** [comment]
Thank you for this tips. I was trying to make a port from ofxGui to ofxDatGui and I had a very ofVec2Slider.

**Comment by braitsch** [comment]
The example @mattfelsen provided works fine in the latest version on master.
