### ISSUE TITLE
issue with OF 10 on Xcode 9.4

### ISSUE THREAD

**Issue by cyrstem** [braitsch/ofxDatGui#152]
im trying to compile the examples 
 and i get  this error...
/Users/blackbox/of_v0.10.0_osx_release/addons/ofxDatGui/src/libs/ofxSmartFont/ofxSmartFont.h:35:9: Unknown type name 'string'; did you mean 'std::string'    ??
like 19 times any idea how to fix this i try the developer  and the masters

**Comment by mattfelsen** [comment]
Check out this issue with a fix, and also it looks like there's a fix on the `dev` branch
https://github.com/braitsch/ofxDatGui/issues/144

**Comment by braitsch** [comment]
This is resolved with #144 which is now merged in with master.
