### ISSUE TITLE
problem getting focus on hover

### ISSUE THREAD

**Issue by martialgallorini** [braitsch/ofxDatGui#17]
hello,

i am facing a problem, i have two gui (panels).
when i launch the app, hovering the guis doesn't affect it. I need to click once on a gui to get focus. Then when moving to the other gui is the same, i need to click once more to get the focus to the second gui. And so on back and forth

**Comment by braitsch** [comment]
Only one panel can have focus at a time. This is to prevent a panel from receiving unwanted events when another panel is dragged over it. This was added to resolve #2. I can expose a ```gui->setFocus()``` method that will allow you to programmatically assign focus however still only panel will be allowed to have focus at a time.

**Comment by martialgallorini** [comment]
I don't really see the problem here. I mean maybe this is a technical thing which i don't understand as i am not the developper. But it is quite annoying and an ergonomic issue. But that is my opinion.
I don't see such a behavior in ofxUI or core ofxGui addons.

**Comment by braitsch** [comment]
Focus logic is complicated as there are many use cases to consider particularly because each component can exist within a gui panel as well as on its own. Focus management on both a component and gui panel level will continue to improve over time.

**Comment by martialgallorini** [comment]
ok. Thanks for the info.

I will use ofxDatGui for some more test apps or prototypes and add some feedbacks here, but i will keep using ofxGui core addon for production apps until things mature a little.

great work though
