### ISSUE TITLE
Problem with mouse events and panels

### ISSUE THREAD

**Issue by gorkacortazar** [braitsch/ofxDatGui#18]
This is probably related to #17 

I have a matrix button that show and hide several GUI panels. When I hide a gui panel, without any initial interaction, it never gets the mouse events back when is shown; only the ones that I move in the first interaction work after being hidden and shown again.

**Comment by braitsch** [comment]
As I noted on #17 only one panel can have focus at a time. Currently to assign focus to a panel you have to select it although I'll probably add a ``gui->setFocus()`` method that will allow you to assign focus programmatically.

**Comment by gorkacortazar** [comment]
That sounds a good solution for me

**Comment by braitsch** [comment]
Just pushed up 02e935f57ab4c721da69713309eaced4ee1a3eca. Panels now automatically capture focus when they're created however you can now manually set which panel has focus via ```gui->setFocus()```

```
// create four panels side by side //
panel1 = new ofxDatGui(0, 0);
panel2 = new ofxDatGui(panel1->getWidth(), 0);
panel3 = new ofxDatGui(panel1->getWidth()*2, 0);
panel4 = new ofxDatGui(panel1->getWidth()*3, 0);
```
When this runs the last panel created will have focus (panel 4). 
After all panels have been created you can manually reassign focus via:
```
panel3->setFocus();
```

**Comment by braitsch** [comment]
In response to this: 

*"When I hide a gui panel, without any initial interaction, it never gets the mouse events back when is shown"*

Are you hiding the panels by setting its visibility to false or are you disabling them?
I'm not sure I understand the problem, please describe steps to recreate.

**Comment by gorkacortazar** [comment]
I will isolate the example today, but the order is basically this:

- Each class creates its own GUI panel
- All GUI panels are hidden after being created (toggling the visibility, not disabling them)
- An extra panel (matrix) decides which panel to show
- When I toggle the visibility of a panel, doesn't get focus nor accepts mouse events

It is very weird because in my app, from 15 panels, two of them accept the mouse input, from 12 different ones. But if don't hide them at the beginning, and instead manually move panels before hiding them, they recover the focus when shown.

I'll check today if the updates solves the issue.
