### ISSUE TITLE
Mouse Event doesn't stop

### ISSUE THREAD

**Issue by gorkacortazar** [braitsch/ofxDatGui#2]
When you have more tan one panel overlapping, the mouse events should stop after the topmost element that receivet it.

You can actívate two buttons on top of each other or drag more tan one panel at the same time, for example.

**Comment by braitsch** [comment]
Yeah, I need to create a panel manager (or static methods on ofxDatGui) to manage focus across multiple panels. This is quite high on the list and should be coming in the next week or so.

**Comment by braitsch** [comment]
@gorkacortazar Hi, I finally got around to addressing this and think I've got it resolved with c45865fa75bdf64a345d7969a7ad35a601ad937a. If you don't mind pull down the latest and let me know when you have a chance. Thanks.

**Comment by gorkacortazar** [comment]
Works perfectly on Visual Studio 2015
