### ISSUE TITLE
Plotter::update vector out of range

### ISSUE THREAD

**Issue by micuat** [braitsch/ofxDatGui#22]
The plotter's update function crashes at https://github.com/braitsch/ofxDatGui/blob/master/src/components/ofxDatGuiTimeGraph.h#L290

I added **else if** to the second if statement, and it seems working fine:

```
            while(i < pts.size())
            {
                if (pts.at(i).x <= 0) pts.erase(pts.end() - 1);
                else if (pts.at(i).x <= mSpeed) pts.at(i).x = mLineWeight / 2;
                i++;
            }
```

**Comment by braitsch** [comment]
I haven't been able to reproduce this issue however I added your else statement nonetheless.
Feel free to reopen if you feel its unresolved.
