### ISSUE TITLE
ofxDatGui draw should push/pop style and  call ofFill

### ISSUE THREAD

**Issue by crucialfelix** [braitsch/ofxDatGui#23]
First off - great job on this project, very elegant and nicely documented !

In `ofxDatGui::draw` you should insulate (you probably already are) and make sure `ofFill()` is called:

```cpp
ofPushStyle();
ofFill();
...
ofPopStyle();
```

Its me actually that was bad here — I called `ofNoFill()` and didn't push/pop — and this caused `ofDatGui` to render incorrectly.

So it looked like this:

![if-mouse-is-not-down](https://cloud.githubusercontent.com/assets/218738/10967173/eb7473e0-83b8-11e5-9672-41d9c31915e9.png)

thanks again !

**Comment by braitsch** [comment]
Hi, thanks for bringing this to my attention. ofxDatGui now calls ``ofFill()`` within its draw method so it should now render correctly regardless of what happens in the main application's draw call.

**Comment by crucialfelix** [comment]
Splendid, nice one !
