### ISSUE TITLE
ofxDatGuiTextInput receives invalid characters (like SHIFT)

### ISSUE THREAD

**Issue by nervoussystem** [braitsch/ofxDatGui#25]
When typing in an ofxDatGuiTextInput special characters like SHIFT, LEFT_SHIFT, ALT, etc get added to the string. This can be problematic when using the input box for something like a filename.

**Comment by braitsch** [comment]
Hi I just checked this on OSX and I'm not seeing this behavior. Are Ascii codes getting appended? What are you seeing when you when you print out the contents of the textfield?

```
cout << gui->getTextInput("textfield name")->getText() << endl;
```

**Comment by nervoussystem** [comment]
I am on Windows, Visual Studio 2015. When I type something with shift, it
appears in the console as spaces and smiley faces. I can't paste it in but
I can send a screenshot. If I print out the key codes its adding, it adds
two for every shift press, one 2304 for SHIFT and one 2305 for LEFT_SHIFT.

My workaround was to change the else case in keyIsValid to:
return key != OF_KEY_ALT && key != OF_KEY_SHIFT && key != OF_KEY_CONTROL &&
key != OF_KEY_COMMAND && key != OF_KEY_ESC && key != OF_KEY_TAB && key !=
OF_KEY_LEFT_SHIFT && key != OF_KEY_RIGHT_SHIFT

On Wed, Nov 18, 2015 at 5:08 PM, braitsch <notifications@github.com> wrote:

> Hi I just checked this on OSX and I'm not seeing this behavior. Are Ascii
> codes getting appended? What are you seeing when you when you print out the
> contents of the textfield?
>
> cout << gui->getTextInput("textfield name")->getText() << endl;
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/braitsch/ofxDatGui/issues/25#issuecomment-157880261>.
>



-- 
Jesse Louis-Rosenberg
Nervous System
http://n-e-r-v-o-u-s.com

**Comment by braitsch** [comment]
I just noticed it was capturing my caps lock & function keys so I just pushed up a patch 8b3c79819da5670d6dbd920ffc44954846bcae24 that should now ignore all non-printable characters (anything outside of the ascii range of 32 to 255). If you wouldn't mind please let me know if that resolves the issue on Windows.

**Comment by nervoussystem** [comment]
Seems to be missing a return false at the end. And needs to permit
backspace.

On Wed, Nov 18, 2015 at 5:28 PM, braitsch <notifications@github.com> wrote:

> I just noticed it was capturing my caps lock & function keys so I just
> pushed up a patch 8b3c798
> <https://github.com/braitsch/ofxDatGui/commit/8b3c79819da5670d6dbd920ffc44954846bcae24>
> that should now ignore all non-printable characters (anything outside of
> the ascii range of 32 to 255). If you wouldn't mind please let me know if
> that resolves the issue on Windows.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/braitsch/ofxDatGui/issues/25#issuecomment-157885330>.
>



-- 
Jesse Louis-Rosenberg
Nervous System
http://n-e-r-v-o-u-s.com

**Comment by braitsch** [comment]
Just pushed up 80e3fc81699ffea3facbd1562768f2f463eef3c2 to address the above. I'm currently allowing the [entire printable ascii range (32-255)] (http://www.ascii-code.com/) which has a couple of empty characters in the extended range (128-255) so if it's still acting weird I'll pull it back to just (32-127)

**Comment by braitsch** [comment]
Closing as resolved.
