### ISSUE TITLE
How to use onButtonEvent inside class?

### ISSUE THREAD

**Issue by Arseniusz** [braitsch/ofxDatGui#26]
Hello. I trying to make a class that contain a button and toggle together, but in not react on onButtonEvent() (if I use same code outside my class in ofApp all works perfect ). How can I give ofApp context to onButtonEvent constructor inside a class?

**Comment by braitsch** [comment]
Response posted here: http://forum.openframeworks.cc/t/use-ofxdatgui-inside-class/21584
