### ISSUE TITLE
Feature: cursor for text input

### ISSUE THREAD

**Issue by nervoussystem** [braitsch/ofxDatGui#27]
Add a cursor to ofxDatGuiTextInputField to allow mid string editing.

**Comment by braitsch** [comment]
Resolved by #28

**Comment by sinedied** [comment]
Seems like the cursor does not play well with retina displays:

<img width="444" alt="capture d ecran 2017-02-10 a 14 38 39" src="https://cloud.githubusercontent.com/assets/593151/22828630/a4e1ed92-ef9e-11e6-917d-4d2b1316ba7c.png">

The cursor should be at the right end on the capture.

**Comment by braitsch** [comment]
I just noticed this as well a few days ago. Something must've changed in a recent version of OF. It used to work fine in 0.9.2, will investigate.
