### ISSUE TITLE
Modifying slider controls ofEasyCam as well.

### ISSUE THREAD

**Issue by jossgray** [braitsch/ofxDatGui#29]
You you drag around on a slider with an ofEasyCam instance, the camera rotation is modified.

**Comment by braitsch** [comment]
That's because it's listening for the same global mouse events as the slider. You can decouple the camera from mouse events in your slider event handler via:

    void ofApp::onSliderEvent(ofxDatGuiSliderEvent e)
    {
        cam.disableMouseInput();
    }
