### ISSUE TITLE
Changing the GUI origin does not affect the elements inside it

### ISSUE THREAD

**Issue by razvanilin** [braitsch/ofxDatGui#3]
I am not sure if this is done on purpose, but if I modify the origin of the gui, the elements inside it don't get updated. Take a look at the attached picture to see what I mean. The gui has the green background and it always gets updated with new origin values when the window is resized. The elements, though, remain in the same position.

Is there a way of updating the origin of all the elements to match gui's new position?

![issue](https://cloud.githubusercontent.com/assets/5342321/10279611/0561eec6-6b5f-11e5-9cc4-05ea7daea210.JPG)

**Comment by braitsch** [comment]
Thanks, this should now be fixed with 9e4058e29373c1df8a79bb533dc7f6808ca0aeab

**Comment by razvanilin** [comment]
Forgot to say this, but thank you for the quick fix. It works now :+1:
