### ISSUE TITLE
widgets suggestion and small bug report

### ISSUE THREAD

**Issue by sebescudie** [braitsch/ofxDatGui#30]
hello,
first of all thanks for this awesome addon!

I have a small liste of suggestions :

* rotary sliders
* the ability to set "ticks" on a slider
* double-clic or left-clic on a slider to reset it to a default value
* the ability to "fine-tune" a slider by shift+draging it

does that seem relevant/feasible?

also, i've noticed that when you stack three sliders on top of each other, if the one in the middle has the focus and you drag your mouse on the one on the top (with LMB pressed), it instantly takes focus. This does not seem to happen with the lower slider.

thanks!

**Comment by braitsch** [comment]
Hi thanks for the suggestions. Rotary sliders/dials are a good idea, I'll add them to the roadmap.

As for the mouse behavior, that's just how it works for now as the components in the gui are scanned for focus from the top down. I may rewrite this at some point but for right now I don't see it as a usability issue.

**Comment by sebescudie** [comment]
thanks for the rotary sliders !

concerning the focus behavior, of course that's not an urgent issue but it leads to undesired value changes if your cursor goes above the mid-slider. I'll try to be more careful when moving the sliders.

thanks!
