### ISSUE TITLE
Many warnings when compiling with -Wall flag.

### ISSUE THREAD

**Issue by rvega** [braitsch/ofxDatGui#31]
There are many compiler warnings. We should get rid of those :)

**Comment by rvega** [comment]
https://github.com/braitsch/ofxDatGui/pull/32

**Comment by rvega** [comment]
Hi. Any reason why this was not merged? Maybe you can suggest another way to get rid of the compiler warnings?

**Comment by kritzikratzi** [comment]
almost all changes are casting the loop variable, like 

    - for (int i=0; i<trash.size(); i++)
    + for (int i=0; i<(int)trash.size(); i++)

casting to int is sortof the wrong thing to do here. you can either use a `size_t` for the counter, or use a c++11 loop. 

    for( size_t i = 0; i<trash.size(); i++){...}
    or 
    for( auto t : trash ){...}
