### ISSUE TITLE
Data binding notes

### ISSUE THREAD

**Issue by neilmendoza** [braitsch/ofxDatGui#33]
Great work with this addon! Been playing around with it a bit and had a few notes about binding...

* When you bind a variable like this...

  gui->addSlider("name", 0.f, 1.f)->bind(&variable, 0.f, 1.f);

  ...you end up giving the min and max twice. Might be nice to have some kind of shorthand that does it     automatically if you pass a pointer to the gui. 

* For me, I think it would be nice if you passed a reference rather than a pointer to the bind function but that's probably a subjective thing. 

* When you bind a variable you still get warnings that an event handler has not been created.

Thanks!

**Comment by braitsch** [comment]
Hi, I'm rewriting data binding to add support for ofParameter so the API will be changing quite a bit in the next release.

There's a [sample project](https://github.com/braitsch/ofxDatGui/blob/dev/example-ofParameter/src/ofApp.cpp) on the dev branch that I'll be updating as it comes along.

**Comment by braitsch** [comment]
As of v1.1 the bind method now also accepts just a variable and the min/max values can be set/updated separately via their own methods. 

I also agree with you it's cleaner to pass variables to the bind method by reference.

To suppress warnings about the event handler not being set you can -> ofxDatGuiLog::quiet();
