### ISSUE TITLE
fonts

### ISSUE THREAD

**Issue by andreirt** [braitsch/ofxDatGui#35]
I download this addon some weeks ago, and it was working fine in a multi window app. Now, when I pulled last changes, fonts are always invalid. It is like pointers to fonts are being deleted / lost somewhere. I am going to study this commit later:

https://github.com/braitsch/ofxDatGui/commit/2f6ad8e938c0dcac846d6e1b6ae7be1834ed8f4d

Best,
Andrie

**Comment by braitsch** [comment]
I wrote [ofxSmartFont](https://github.com/braitsch/ofxSmartFont) to address this issue of fonts potentially going out of scope and being deleted. 
It will be a part of ofxDatGui in the next release.

**Comment by andreirt** [comment]
Great, thank you. For now, I am using a commit of November 30. I created two controls, a button that shows an image, and a matrix of image buttons. I will wait for the next release to submit a pull request but, if you would like to give a look, I can send you the code. I used two different approaches, and would like to receive feedback about how would be the best way to create new controls, if you have time:

- for ofxDatGuiImageMatrix, I created a class based on ofxDatGuiMatrix, subclassing ofxDatGuiComponent. I have created a class for events (ofxDatGuiImageMatrixEvent), and added some methods to ofxDatGui ofxDatGuiFolder

for ofxDatGuiImage, I have just subclasse ofxDatGuiButton. It works, but it seems a little dirty and lazy for me. I think the approach I took for ofxDatGuiImageMatrix is much better. 


Best,
Andrei

**Comment by braitsch** [comment]
ofxSmartFont is now included in ofxDatGui to ensure fonts never go out of scope. 
Free free reopen this issue if you're still seeing invalid fonts. 552900b6be8564a7d93d4f7881adddabc80cdeaf

**Comment by michelson** [comment]
Hi , I just download the latest release but can't see the fonts , 
I've run the examples projects and I see the same issue

error in console is:

```
[warning] ofGLRenderer: drawing an unallocated texture
[ error ] ofTrueTypeFont: drawString(): font not allocated
```

**Comment by braitsch** [comment]
@michelson what platform are you on?

**Comment by michelson** [comment]
osx , OF 0.9.0

**Comment by braitsch** [comment]
I just cloned the repo into my 0.9.0 addons folder and everything works fine for me. You're saying that  the examples projects are unable to load the font files? Can you confirm that the ofxbraitsch directory that contains the fonts is located in your project's /bin/data folder?

**Comment by michelson** [comment]
Hi @braitsch thanks for your quick reply , 
here are the screenshots , 
![image](https://cloud.githubusercontent.com/assets/11976/14763840/f502dd2a-0978-11e6-9e86-d773cd2ae7dc.png)

![image](https://cloud.githubusercontent.com/assets/11976/14763825/a75f6a02-0978-11e6-9225-c363ccfeea6e.png)

**Comment by michelson** [comment]
Ah , I've renamed the folder from ofxDatGui-[release-version] to just ofxDatGui and it works!

**Comment by braitsch** [comment]
great! glad you got it working. lmk if you run into any other issues.
