### ISSUE TITLE
compile on raspberry pi b+ raspbian jessie 4.1.13+ #826 OF090

### ISSUE THREAD

**Issue by dammianhr** [braitsch/ofxDatGui#38]
i have this error when try to compile any example:

HOST_OS=Linux
HOST_ARCH=armv6l
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gtk+-3.0 
Compiling OF library for Release
make[1]: Entering directory '/home/pi/openFrameworks/libs/openFrameworksCompiled/project'
HOST_OS=Linux
HOST_ARCH=armv6l
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gtk+-3.0 
HOST_OS=Linux
HOST_ARCH=armv6l
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gtk+-3.0 
HOST_OS=Linux
HOST_ARCH=armv6l
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gtk+-3.0 
Done!
make[1]: Leaving directory '/home/pi/openFrameworks/libs/openFrameworksCompiled/project'

Compiling example-Matrices for Release
make[1]: Entering directory '/home/pi/openFrameworks/addons/ofxDatGui/example-Matrices'
HOST_OS=Linux
HOST_ARCH=armv6l
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gtk+-3.0 
cat: obj/linuxarmv6l/Release/.compiler_flags: No such file or directory
Compiling /home/pi/openFrameworks/addons/ofxDatGui/example-Matrices/src/main.cpp
g++ -c -O3 -DNDEBUG -Wall -std=c++14 -DGCC_HAS_REGEX -march=armv6 -mfpu=vfp -mfloat-abi=hard -fPIC -ftree-vectorize -Wno-psabi -pipe -DOF_USING_GTK -DOF_USING_GTK -DTARGET_RASPBERRY_PI -DSTANDALONE -DPIC -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DTARGET_POSIX -DHAVE_LIBOPENMAX=2 -DOMX -DOMX_SKIP64BIT -DUSE_EXTERNAL_OMX -DHAVE_LIBBCM_HOST -DUSE_EXTERNAL_LIBBCM_HOST -DUSE_VCHIQ_ARM  -I/opt/vc/include -I/opt/vc/include/IL -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux -D_REENTRANT -pthread -I/usr/include/gstreamer-1.0 -I/usr/include/AL -I/usr/include/alsa -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/arm-linux-gnueabihf/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/home/pi/openFrameworks/libs/fmodex/include -I/home/pi/openFrameworks/libs/glfw/include -I/home/pi/openFrameworks/libs/glfw/include/GLFW -I/home/pi/openFrameworks/libs/kiss/include -I/home/pi/openFrameworks/libs/poco/include -I/home/pi/openFrameworks/libs/tess2/include -I/home/pi/openFrameworks/libs/utf8cpp/include -I/home/pi/openFrameworks/libs/utf8cpp/include/utf8 -I/home/pi/openFrameworks/libs/openFrameworks -I/home/pi/openFrameworks/libs/openFrameworks/gl -I/home/pi/openFrameworks/libs/openFrameworks/video -I/home/pi/openFrameworks/libs/openFrameworks/events -I/home/pi/openFrameworks/libs/openFrameworks/communication -I/home/pi/openFrameworks/libs/openFrameworks/math -I/home/pi/openFrameworks/libs/openFrameworks/sound -I/home/pi/openFrameworks/libs/openFrameworks/graphics -I/home/pi/openFrameworks/libs/openFrameworks/utils -I/home/pi/openFrameworks/libs/openFrameworks/types -I/home/pi/openFrameworks/libs/openFrameworks/app -I/home/pi/openFrameworks/libs/openFrameworks/3d -I/home/pi/openFrameworks/addons/ofxDatGui/example-Matrices/src -I/home/pi/openFrameworks/addons/ofxDatGui/example-Matrices/example-Matrices.xcodeproj/xcshareddata -I/home/pi/openFrameworks/addons/ofxDatGui/example-Matrices/example-Matrices.xcodeproj/xcshareddata/xcschemes -I/home/pi/openFrameworks/addons/ofxDatGui/src -I/home/pi/openFrameworks/addons/ofxDatGui/src/themes -I/home/pi/openFrameworks/addons/ofxDatGui/src/core -I/home/pi/openFrameworks/addons/ofxDatGui/src/components -MMD -MP -MF obj/linuxarmv6l/Release/src/main.d -MT obj/linuxarmv6l/Release/src/main.o -o obj/linuxarmv6l/Release/src/main.o -c /home/pi/openFrameworks/addons/ofxDatGui/example-Matrices/src/main.cpp
In file included from /opt/vc/include/interface/vcos/vcos.h:116:0,
                 from /opt/vc/include/interface/vmcs_host/vc_dispmanx.h:33,
                 from /opt/vc/include/bcm_host.h:50,
                 from /home/pi/openFrameworks/libs/openFrameworks/utils/ofConstants.h:169,
                 from /home/pi/openFrameworks/libs/openFrameworks/ofMain.h:5,
                 from /home/pi/openFrameworks/addons/ofxDatGui/example-Matrices/src/main.cpp:1:
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h: In function 'void vcos_event_signal(VCOS_EVENT_T*)':
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:535:8: warning: variable 'ok' set but not used [-Wunused-but-set-variable]
    int ok = 0;
        ^
In file included from /home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiGroups.h:26:0,
                 from /home/pi/openFrameworks/addons/ofxDatGui/src/ofxDatGui.h:24,
                 from /home/pi/openFrameworks/addons/ofxDatGui/example-Matrices/src/ofApp.h:4,
                 from /home/pi/openFrameworks/addons/ofxDatGui/example-Matrices/src/main.cpp:2:
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiSlider.h: In member function 'void ofxDatGuiSlider::setTextInput()':
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiSlider.h:342:38: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 while(v.length() - p < (mPrecision+1)) v+='0';
                                      ^
In file included from /home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiGroups.h:31:0,
                 from /home/pi/openFrameworks/addons/ofxDatGui/src/ofxDatGui.h:24,
                 from /home/pi/openFrameworks/addons/ofxDatGui/example-Matrices/src/ofApp.h:4,
                 from /home/pi/openFrameworks/addons/ofxDatGui/example-Matrices/src/main.cpp:2:
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiMatrix.h: In member function 'virtual void ofxDatGuiMatrix::setWidth(int, float)':
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiMatrix.h:178:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for(int i=0; i<btns.size(); i++){
                           ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiMatrix.h: In member function 'virtual bool ofxDatGuiMatrix::hitTest(ofPoint)':
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiMatrix.h:202:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 for(int i=0; i<btns.size(); i++) btns[i].hitTest(m, mMouseDown);
                               ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiMatrix.h:205:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 for(int i=0; i<btns.size(); i++) btns[i].onMouseOut();
                               ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiMatrix.h: In member function 'virtual void ofxDatGuiMatrix::draw()':
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiMatrix.h:217:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 for(int i=0; i<btns.size(); i++) btns[i].draw(x+mLabel.width, y);
                               ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiMatrix.h: In member function 'void ofxDatGuiMatrix::clear()':
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiMatrix.h:223:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for (int i=0; i<btns.size(); i++) btns[i].setSelected(false);
                            ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiMatrix.h: In member function 'void ofxDatGuiMatrix::setSelected(std::vector<int>)':
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiMatrix.h:229:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for (int i=0; i<v.size(); i++) btns[v[i]].setSelected(true);
                            ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiMatrix.h: In member function 'std::vector<int> ofxDatGuiMatrix::getSelected()':
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiMatrix.h:235:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for(int i=0; i<btns.size(); i++) if (btns[i].getSelected()) selected.push_back(i);
                           ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiMatrix.h: In member function 'virtual void ofxDatGuiMatrix::onMouseRelease(ofPoint)':
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiMatrix.h:252:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for(int i=0; i<btns.size(); i++) btns[i].onMouseRelease(m);
                           ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiMatrix.h: In member function 'void ofxDatGuiMatrix::onButtonSelected(ofxDatGuiInternalEvent)':
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiMatrix.h:259:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 for(int i=0; i<btns.size(); i++) btns[i].setSelected(e.index == i);
                               ^
In file included from /home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiGroups.h:32:0,
                 from /home/pi/openFrameworks/addons/ofxDatGui/src/ofxDatGui.h:24,
                 from /home/pi/openFrameworks/addons/ofxDatGui/example-Matrices/src/ofApp.h:4,
                 from /home/pi/openFrameworks/addons/ofxDatGui/example-Matrices/src/main.cpp:2:
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiTimeGraph.h: In member function 'virtual void ofxDatGuiTimeGraph::draw()':
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiTimeGraph.h:80:74: error: 'glColor3ub' was not declared in this scope
                 glColor3ub(mColor.fills.r, mColor.fills.g, mColor.fills.b);
                                                                          ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiTimeGraph.h: In member function 'void ofxDatGuiTimeGraph::drawFilled()':
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiTimeGraph.h:89:46: error: 'GL_FILL' was not declared in this scope
             glPolygonMode(GL_FRONT_AND_BACK, GL_FILL);
                                              ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiTimeGraph.h:89:53: error: 'glPolygonMode' was not declared in this scope
             glPolygonMode(GL_FRONT_AND_BACK, GL_FILL);
                                                     ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiTimeGraph.h:90:38: error: 'glBegin' was not declared in this scope
             glBegin(GL_TRIANGLE_STRIP);
                                      ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiTimeGraph.h:91:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for (int i=0; i<pts.size(); i++) {
                            ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiTimeGraph.h:92:66: error: 'glVertex2f' was not declared in this scope
                 glVertex2f(px+ pts[i].x, py + mPlotterRect.height);
                                                                  ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiTimeGraph.h:95:19: error: 'glEnd' was not declared in this scope
             glEnd();
                   ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiTimeGraph.h: In member function 'void ofxDatGuiTimeGraph::drawOutline()':
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiTimeGraph.h:103:33: error: 'glBegin' was not declared in this scope
             glBegin(GL_LINE_LOOP);
                                 ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiTimeGraph.h:104:69: error: 'glVertex2f' was not declared in this scope
             glVertex2f(px+mPlotterRect.width, py+mPlotterRect.height);
                                                                     ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiTimeGraph.h:105:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for (int i=0; i<pts.size(); i++) glVertex2f(px+pts[i].x, py+pts[i].y);
                            ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiTimeGraph.h:107:19: error: 'glEnd' was not declared in this scope
             glEnd();
                   ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiTimeGraph.h: In member function 'void ofxDatGuiTimeGraph::drawLines()':
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiTimeGraph.h:115:34: error: 'glBegin' was not declared in this scope
             glBegin(GL_LINE_STRIP);
                                  ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiTimeGraph.h:116:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for (int i=0; i<pts.size(); i++) glVertex2f(px+pts[i].x, py+pts[i].y);
                            ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiTimeGraph.h:116:81: error: 'glVertex2f' was not declared in this scope
             for (int i=0; i<pts.size(); i++) glVertex2f(px+pts[i].x, py+pts[i].y);
                                                                                 ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiTimeGraph.h:117:19: error: 'glEnd' was not declared in this scope
             glEnd();
                   ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiTimeGraph.h: In member function 'void ofxDatGuiTimeGraph::drawPoints()':
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiTimeGraph.h:126:30: error: 'glBegin' was not declared in this scope
             glBegin(GL_POINTS);
                              ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiTimeGraph.h:127:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for (int i=0; i<pts.size(); i++) glVertex2f(px+pts[i].x, py+pts[i].y);
                            ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiTimeGraph.h:127:81: error: 'glVertex2f' was not declared in this scope
             for (int i=0; i<pts.size(); i++) glVertex2f(px+pts[i].x, py+pts[i].y);
                                                                                 ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiTimeGraph.h:128:19: error: 'glEnd' was not declared in this scope
             glEnd();
                   ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiTimeGraph.h: In member function 'virtual void ofxDatGuiValuePlotter::update(bool)':
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiTimeGraph.h:286:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for (int i=0; i<pts.size(); i++) pts[i].x -= mSpeed;
                            ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiTimeGraph.h:288:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             while(i < pts.size())
                     ^
In file included from /home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiGroups.h:33:0,
                 from /home/pi/openFrameworks/addons/ofxDatGui/src/ofxDatGui.h:24,
                 from /home/pi/openFrameworks/addons/ofxDatGui/example-Matrices/src/ofApp.h:4,
                 from /home/pi/openFrameworks/addons/ofxDatGui/example-Matrices/src/main.cpp:2:
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiScrollView.h: In member function 'void ofxDatGuiScrollView::move(ofxDatGuiComponent*, int)':
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiScrollView.h:89:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for(int i=0; i<children.size(); i++){
                           ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiScrollView.h: In member function 'void ofxDatGuiScrollView::remove(ofxDatGuiComponent*)':
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiScrollView.h:113:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for(int i=0; i<children.size(); i++){
                           ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiScrollView.h: In member function 'void ofxDatGuiScrollView::onMouseScrolled(ofMouseEventArgs&)':
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiScrollView.h:259:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                     for(int i=0; i<children.size(); i++) children[i]->setPosition(0, topY + (btnH * i));
                                   ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiScrollView.h: In member function 'void ofxDatGuiScrollView::onButtonEvent(ofxDatGuiButtonEvent)':
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiScrollView.h:268:22: warning: statement has no effect [-Wunused-value]
                 for(i; i<children.size(); i++) if (children[i] == e.target) break;
                      ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiScrollView.h:268:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 for(i; i<children.size(); i++) if (children[i] == e.target) break;
                         ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiScrollView.h: In member function 'bool ofxDatGuiScrollView::isValidIndex(int)':
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiScrollView.h:287:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             return index >= 0 && index < children.size();
                                        ^
In file included from /home/pi/openFrameworks/addons/ofxDatGui/src/ofxDatGui.h:24:0,
                 from /home/pi/openFrameworks/addons/ofxDatGui/example-Matrices/src/ofApp.h:4,
                 from /home/pi/openFrameworks/addons/ofxDatGui/example-Matrices/src/main.cpp:2:
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiGroups.h: In member function 'virtual void ofxDatGuiGroup::draw()':
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiGroups.h:83:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                     for(int i=0; i<children.size(); i++) {
                                   ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiGroups.h:87:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                         if (i == children.size()-1) break;
                               ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiGroups.h:91:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                     for(int i=0; i<children.size(); i++) children[i]->drawColorPicker();
                                   ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiGroups.h: In member function 'void ofxDatGuiGroup::layout()':
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiGroups.h:102:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for (int i=0; i<children.size(); i++) {
                            ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiGroups.h:110:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 if (i == children.size()-1) mHeight -= mStyle.vMargin;
                       ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiGroups.h: In member function 'virtual void ofxDatGuiFolder::drawColorPicker()':
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiGroups.h:172:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for(int i=0; i<pickers.size(); i++) pickers[i]->drawColorPicker();
                           ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiGroups.h: In member function 'ofxDatGuiComponent* ofxDatGuiFolder::getComponent(ofxDatGuiType, std::string)':
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiGroups.h:351:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for (int i=0; i<children.size(); i++) {
                            ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiGroups.h: In constructor 'ofxDatGuiDropdown::ofxDatGuiDropdown(std::string, const std::vector<std::basic_string<char> >&)':
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiGroups.h:401:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for(int i=0; i<options.size(); i++){
                           ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiGroups.h: In member function 'void ofxDatGuiDropdown::select(int)':
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiGroups.h:429:38: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (cIndex < 0 || cIndex >= children.size()){
                                      ^
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiGroups.h: In member function 'void ofxDatGuiDropdown::onOptionSelected(ofxDatGuiButtonEvent)':
/home/pi/openFrameworks/addons/ofxDatGui/src/components/ofxDatGuiGroups.h:457:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for(int i=0; i<children.size(); i++) if (e.target == children[i]) mOption = i;
                           ^
/home/pi/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:199: recipe for target 'obj/linuxarmv6l/Release/src/main.o' failed
make[1]: *** [obj/linuxarmv6l/Release/src/main.o] Error 1
make[1]: Leaving directory '/home/pi/openFrameworks/addons/ofxDatGui/example-Matrices'
/home/pi/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:126: recipe for target 'Release' failed
make: *** [Release] Error 2

**Comment by braitsch** [comment]
Raspberry PI is not supported.
