### ISSUE TITLE
Gui elements don't appear in example-GenerativeLines

### ISSUE THREAD

**Issue by clayheaton** [braitsch/ofxDatGui#39]
The DatGui elements do not appear in the `example-GenerativeLines`. This appear to be due to the positioning on line 9 of `ofApp.cpp`, which has:

    gui = new ofxDatGui( ofxDatGuiAnchor::TOP_RIGHT );

Change it to the following at the GUI appears:

    gui = new ofxDatGui( ofxDatGuiAnchor::TOP_LEFT );

**Comment by clayheaton** [comment]
Same holds true for `example-OscillatingPolygon`. Perhaps the problem is with the `TOP_RIGHT` positioning?

**Comment by braitsch** [comment]
I'm assuming you're building against 0.9.1? There's currently an [issue with ``ofGetWidth()`` returning incorrect values](https://github.com/openframeworks/openFrameworks/issues/4746) when retina is enabled which is positioning the gui offscreen.

**Comment by clayheaton** [comment]
That's correct. I did not have high density display enabled in the oF app when I noticed it, but I do have a retina screen.

**Comment by braitsch** [comment]
As of 0.9.1 there is a bug in the oF window resize handler that is incorrectly setting the window dimensions. https://github.com/openframeworks/openFrameworks/pull/4844

**Comment by braitsch** [comment]
[This will be fixed in 0.9.3](https://github.com/openframeworks/openFrameworks/pull/4858)
