### ISSUE TITLE
Text inputs are defaulting any input to upper case

### ISSUE THREAD

**Issue by razvanilin** [braitsch/ofxDatGui#4]
This seems like it should be a basic configuration in the template, but I can't seem to make my text inputs to not default everything to upper case. 

Is it possible to configure the text input to normal typing? 

![issue2](https://cloud.githubusercontent.com/assets/5342321/10364650/1dcccae6-6db5-11e5-90f6-8797833484da.JPG)

**Comment by razvanilin** [comment]
I had to comment out a line from `ofxDatGuiTextInputField.h` to make it behave properly.

```
 void onKeyPressed(int key)
        {
            if (!keyIsValid(key)) return;
            if (mHighlightText) mText = "";
            if (key!=OF_KEY_BACKSPACE){
                mText += key;
            }   else {
                if (mText.size() > 0) mText.resize(mText.size()-1);
            }
            mHighlightText = false;
            //setText(ofToUpper(mText));
        }
```

**Comment by braitsch** [comment]
Agreed. I just added flags to ofxDatGuiTemplate that will allow you to disable forced uppercase on both text inputs & labels.

```cpp
struct {
    float width = 320;
    float height = 26;
    float padding = 2;
    float spacing = 1;
    float stripeWidth = 2;
    bool forceUpperCase = true;
} row;
struct {
    bool forceUpperCase = true;
        struct{
            ofColor stripe = ofColor::fromHex(0x1ED36F);
            ofColor text = ofColor::fromHex(0x00FF00);
            ofColor highlight = ofColor::fromHex(0x688EB5);
        } color;
} textInput;
```

**Comment by narner** [comment]
@mattfelsen Quick question; what is the syntax for setting the `forceUpperCase` to yes or no on an instance of a text input or field? Thanks!

**Comment by mattfelsen** [comment]
I'm not positive on the proper or preferred syntax, but I was getting mixed results myself. I tried both creating a a new instance of `ofxDatGuiTheme` & changing the appropriate variables, and also subclassing the theme and overriding. In both cases, the text input value is not uppercased as expected, but the component labels still are. Maybe @braitsch can shed some insight?

```
auto gui = new ofxDatGui(ofxDatGuiAnchor::TOP_LEFT);
auto theme = new ofxDatGuiTheme();
theme->init();
theme->layout.upperCaseLabels = false;
theme->layout.textInput.forceUpperCase = false;
gui->setTheme(theme);
```

Or via subclassing:
```
class MyTheme : public ofxDatGuiTheme {
public:
	MyTheme() {
		layout.upperCaseLabels = false;
		layout.textInput.forceUpperCase = false;
	}
};

auto gui = new ofxDatGui(ofxDatGuiAnchor::TOP_LEFT);
auto theme = new MyTheme();
theme->init();
gui->setTheme(theme);
```

**Comment by braitsch** [comment]
@narner See my comment regarding setting the case of any label or text input [here](https://github.com/braitsch/ofxDatGui/issues/100#issuecomment-250943708).

@mattfelsen That code above works fine for me when I drop it into any of the examples. This API hasn't changed in awhile but just to be safe are you using the latest on master?
