### ISSUE TITLE
Precision of slider is causing non smooth programmatic fades of binded values

### ISSUE THREAD

**Issue by mrbichel** [braitsch/ofxDatGui#42]
I'd much prefer the precision setting only to apply to the display and the input and not to truncate the underlying value. 

In my case I will often bind the sliders to a value that might also get changed programmatically or I might have an ease or filter on the value changes. In the current implementation that results in non smooth animations unless I increase the precision on the slider. For any kind of transition I'd always want as high precision as possible, but on the input slider I might still prefer fewer decimals.

**Comment by braitsch** [comment]
I hear that, although I think most folks expect the underlying value to reflect what the display shows. Let me think about this and where it might make sense to set a flag to unlink the two values. In the meantime you can edit this yourself by removing the calls to ``round()`` in ``calculateScale()`` & ``onMouseDrag()`` and then add it to the ``setTextInput()`` call if you want to show the precision value in the input field.

```
void setTextInput()
    string v = ofToString(round(mVal));
    ...
```

**Comment by mrbichel** [comment]
Yeah I get your point, that you will expect the value to reflect exactly. A flag would be nice.
Thanks for the pointers where to change it.

I guess the default behavior that I would find most useful would be that if inputting through the slider then it rounds the values to the precision of the slider, but when another actor changes the value the gui should respect that value.

The idea being you can bind your parameters to a new gui without any impact on program behavior. 
I am often using ofParameters that I then hook up to controllers and other application through osc, and sometimes even multiple interface widgets in OF, then I'd want all of my gui's to respect that they might be setting the parameter with a different precision.

**Comment by braitsch** [comment]
Hi there, I just added a flag to ```slider->setPrecision(int precision, bool truncate = true)``` that will allow you to prevent the underlying slider value from losing precision while preserving the ability to customize what displays in the input field. Note the default behavior is to truncate the underlying value to match what is shown in the input field however you can easily change this by passing ```false``` as the second argument. Let me know how this works for you or if you have any questions.
