### ISSUE TITLE
ofxDatGui2dPad missing setValue, setPosition setting both value and screen position

### ISSUE THREAD

**Issue by mrbichel** [braitsch/ofxDatGui#45]
getPosition seems to return the value I need. But setPosition places the widget another place on the screen.

I'd propose renaming getPosition to getValue and adding a setValue.

Am I missing something?

**Comment by braitsch** [comment]
Yep it's calling its parent's setPosition method on [line#70](https://github.com/braitsch/ofxDatGui/blob/master/src/components/ofxDatGui2dPad.h#l70) which is what is actually moving the component. This is a bug and I agree the methods should be renamed to better reflect what they do and while maintaining parity with the rest of the API. I'l work on a fix.

**Comment by braitsch** [comment]
Just rewrote this component and added ``getPoint()``, ``setPoint()``, and ``getBounds()`` methods that should give you what you need. Calling ``setPosition()`` now positions the component without affecting the local or world coordinates of the point within the pad.
