### ISSUE TITLE
ofxDatGuiLabel doesn't work.

### ISSUE THREAD

**Issue by 0x0c** [braitsch/ofxDatGui#48]
Hello,
I'm using ofxDatGuiLabel but it not works fine.

		auto label = new ofxDatGuiLabel("my text");
		label->setPosition(0, 0);
		label->setWidth(150, 20);

When I draw `labal`, my application crash caused by EXC_BAD_ACCESS.

![screen shot 2016-03-12 at 1 31 22 am](https://cloud.githubusercontent.com/assets/154327/13708474/2d2ba7a2-e7f2-11e5-9a9f-7ab4c6543a34.png)

I'm using OS X and openframeworks 0.9.0.

Please help me;;

**Comment by braitsch** [comment]
You're scoping your label incorrectly, remove the ``auto`` keyword and declare the label in a header file.

ofApp.h
````
ofxDatGuiLabel * myLabel;
````

ofApp.cpp
````
void ofApp::setup()
{
    myLabel = new ofxDatGuiLabel("my text");
    myLabel->setPosition(100, 100);
    myLabel->setWidth(150, 20);
}
void ofApp::draw()
{
    myLabel->draw();
}
````

**Comment by 0x0c** [comment]
I tried another way, but still not works.
Same problem, crash caused by EXC_BAD_ACCESS.

ofApp.h

````
ofxDatGui *gui;
````

ofApp.cpp

````
void ofApp::setup() {
  this->gui = new ofxDatGui();
  this->gui->addLabel("label");
}
void ofApp::update() {
  this->gui->update();
}
void ofApp::draw() {
  this->gui->draw();
}
````

**Comment by 0x0c** [comment]
I added label in the sample project 'example-AllComponentsGui'.
It's not works.

![screen shot 2016-03-13 at 2 16 56 am](https://cloud.githubusercontent.com/assets/154327/13724211/af8ce826-e8c1-11e5-9daf-44617adaeec1.png)
![screen shot 2016-03-13 at 2 16 59 am](https://cloud.githubusercontent.com/assets/154327/13724212/afc6b2d6-e8c1-11e5-83d0-b784afe96edb.png)

**Comment by braitsch** [comment]
Adding a label to a gui as you wrote above works fine for me. Are you using the latest on master?

**Comment by 0x0c** [comment]
Sorry, my library is old.
It works fine!
Thank you.
