### ISSUE TITLE
reference to '_1' is ambiguous

### ISSUE THREAD

**Issue by dionysiusmarquis** [braitsch/ofxDatGui#49]
Hi,

i just ran into an ambiguous reference. I'm using my own compiled boost version with `openFrameworks` which may couse this error.

```
(24)   .../ofxDatGui/src/ofxDatGui.h
(24)   .../ofxDatGui/src/components/ofxDatGuiGroups.h
(24)   .../ofxDatGui/src/components/ofxDatGuiLabel.h
(24)   .../ofxDatGui/src/core/ofxDatGuiComponent.h
Error:(79, 68) reference to '_1' is ambiguous
```

It would help to fully qualify the placeholder like this: `std::placeholders::_1`.
Does this make sense?

**Comment by braitsch** [comment]
I'm fine with this, will push up a patch in a moment.
