### ISSUE TITLE
Prevent mouse event propagation

### ISSUE THREAD

**Issue by dionysiusmarquis** [braitsch/ofxDatGui#50]
Hi,

if you're using `ofxDatGui` with the default openFrameworks `camera` the mouse events are bubling through. Because of that you will still control the camera rotation while changing a slider value for example.

My current "hack" is this:

```cpp
ofAddListener(ofEvents().mousePressed, this, &myClass::mousePressed, OF_EVENT_ORDER_BEFORE_APP);

bool myClass::mousePressed(ofMouseEventArgs &mouse) {
    float width = this->getWidth();
    float height = footer->getY() + footer->getHeight();

    float x = this->getPosition().x;
    float y = this->getPosition().y;

    return (mouse.x >= x && mouse.x <= x + width && mouse.y >= y && mouse.y <= y + height);
}
```
It uses the footer to determine the current menu size.

Maybe there could be a native option to prevent mouse event bubbling.

**Comment by braitsch** [comment]
This has come up before so I just added a ``gui->isMouseDown()`` method which will return true if the mouse is pressed on an interactive area of a component. You can use this to prevent mouse events from penetrating through the gui (which now detects events before the app) via the following:
````
void ofApp::update()
{
    if (ofGetMousePressed() && gui->getMouseDown() == false){
        // let the app handle the mouse event //
    }
}
````
Also just FYI guis have a ``getHeight()`` method in addition to ``getWidth()`` so you shouldn't have to rely on the footer to calculate a gui's height.

Let me know if this helps.

**Comment by marc-antimodular** [comment]
My simple solution, for active controls:

`
void ofApp::update(){
    if ( gui->getMouseDown() )
        camera.disableMouseInput();
    else
        camera.enableMouseInput();
`
