### ISSUE TITLE
Addon image and font resources not being loaded

### ISSUE THREAD

**Issue by pierrep** [braitsch/ofxDatGui#51]
I'm assuming this works on OSX, but is not cross-platform. I'm on Linux and the addon image resources weren't loading. I fixed this by setting the paths to be the following:
```
string rainbow = "../../../../../addons/ofxDatGui/ofxbraitsch/ofxdatgui/picker-rainbow.png";
string radioOn = "../../../../../addons/ofxDatGui/ofxbraitsch/ofxdatgui/icon-radio-on.png";
string radioOff = "../../../../../addons/ofxDatGui/ofxbraitsch/ofxdatgui/icon-radio-off.png";
string dropdown = "../../../../../addons/ofxDatGui/ofxbraitsch/ofxdatgui/icon-dropdown.png";
```

This is the normal OF behaviour, i.e. that file loading is relative to the data path.
Maybe there's a more elegant way to do this, but I'm not sure.

**Comment by braitsch** [comment]
Thanks for reporting this. I just added a ```ofxDatGui::setAssetPath()``` method that will allow you to customize the location of the ofxbraitsch asset directory and made the default path relative to the location of the addon. LMK if this helps.

**Comment by pierrep** [comment]
Great, will try it out. Otherwise addon works perfectly, thanks for making this :)

**Comment by pierrep** [comment]
That fixed it, thanks

**Comment by braitsch** [comment]
Great, glad to hear you're finding it helpful!

**Comment by transat** [comment]
In my app on a mac I needed to set `gui->setAssetPath("");` to use the app's bin/data folder rather than the addons.

**Comment by braitsch** [comment]
@transat Thanks. This appears related to #65. Looking into this now.
