### ISSUE TITLE
Allow for configurable location of ofxbraitsch folder?

### ISSUE THREAD

**Issue by mattfelsen** [braitsch/ofxDatGui#53]
It'd be great to allow for a configurable setting of the ofxbraitsch data folder. Currently in one of my apps, I changed the [hard-coded paths in the addon](https://github.com/local-projects/ofxDatGui/commit/5c55ab48c3869e869879841f46feb187df49a7f9), but it'd be nice to control this from outside the addon.

I started on this by adding static `ofxDatGui::setDataDir(const std::string& dir)` and `ofxDatGui::getDataDir()` methods, but then we wind up with circular includes since ofxDatGui.h ends up `#include`ing ofxDatGuiThemes.h eventually. You can check out what I did on my branch, but maybe you've got a better approach in mind?
https://github.com/mattfelsen/ofxDatGui/commit/bb3f814ebac64852ebe7c11ecf6ae3e8febaac29

Cheers!

**Comment by braitsch** [comment]
Themes are assigned to guis & components so I'd rather not include a reference to either of them within the ofxDatGuiTheme class. I added a static ofxDatGui convenience method that sets a new ```ofxDatGuiTheme::AssetPath``` variable that will allow you to customize the location of the ofxbraitsch assets directory. LMK if this works for what you need.

**Comment by mattfelsen** [comment]
Oh duh, not sure why I was thinking it had to be a static method on `ofxDatGui`. Perfect! I'll give this a shot later but this should be good for me. Thanks!

**Comment by braitsch** [comment]
Cool, sounds like this works for you. Feel free to reopen if you have any trouble.
