### ISSUE TITLE
Make the Example folder nested

### ISSUE THREAD

**Issue by Flowstoner** [braitsch/ofxDatGui#55]
If you can move the examples in a nested subfolder like:
`example/All_ofxDatGuiExample`
we can use the projectGenerator in 'multiple update' mode
so we can easily update all projects for each platform.

**Comment by braitsch** [comment]
This is unnecessary and it would break how ofxaddons.com currently parses the repository.

**Comment by Flowstoner** [comment]
Ok, I think this should be resolved in the projectGenerator application...
Anyway thank you for your attention, and this wonderful addon.
