### ISSUE TITLE
Making `expandGui` and `collapseGui ` as public APIs?

### ISSUE THREAD

**Issue by nebgnahz** [braitsch/ofxDatGui#57]
I would like the default case of a panel to be **collapsed** to save space on the GUI.

But there doesn't seem to be a way so far (I may be missing something here). And it seems useful in general to make these two function calls public. I can make a pull request if that's helpful for you. Thanks!

**Comment by braitsch** [comment]
Good idea, I'll add this in shortly.

**Comment by braitsch** [comment]
documentation updated to include the [new api calls](https://braitsch.github.io/ofxDatGui/index.html#headers-footers)
