### ISSUE TITLE
Support for Text Blocks (Paragraph) Components

### ISSUE THREAD

**Issue by nebgnahz** [braitsch/ofxDatGui#58]
I am wondering how to add pure texts (a paragraph, for example, to explain some control parameter). 
- `addLabel` works but it capitalized the words; and it can't wrap long texts.
- `addTextInput` requires labels, and the text contents are capitalized/editable.

Any suggestions?

**Comment by braitsch** [comment]
There isn't currently a "text block" or "paragraph" component but you attempt to roll your own by extending the ``ofxDatGuiComponent`` base class and using [ofxParagraph](https://github.com/braitsch/ofxParagraph) to layout & render the text. 

I'll flag this a feature request and take a look at adding this in the next release.

**Comment by nebgnahz** [comment]
Closing as no longer needed.
