### ISSUE TITLE
Library does not compile.

### ISSUE THREAD

**Issue by garrettburnett** [braitsch/ofxDatGui#59]
Hello I get some errors in ofxSmartFont.h when attempting to view any of your examples:
![image](https://cloud.githubusercontent.com/assets/14268490/14037447/1f88e07e-f201-11e5-9880-6d8e377e2597.png)

**Comment by braitsch** [comment]
what platform are you on?

**Comment by garrettburnett** [comment]
Hi I'm on v 8.4, and running the code with SDK OS X 10.9. My 

-Sent from mobile

**Comment by braitsch** [comment]
ofxDatGui requires oF v0.9.0+
