### ISSUE TITLE
Constant POINTS redefinition conflict

### ISSUE THREAD

**Issue by gorkacortazar** [braitsch/ofxDatGui#6]
Some constants causes redefinition conflicts, for example ofxDatGuiGraph::POINTS with and opencv POINTS definition.

I will send a PR to rename the enums to make them ofxDatGui specific.

**Comment by razvanilin** [comment]
Had the same problem after I pulled the latest version

**Comment by braitsch** [comment]
Hi, good catch! I just pushed an update that should resolve this. 7a5be5ac08f369080c54292f4ca6bbc48c117867

C++11 added support for [strongly typed enums](http://www.cprogramming.com/c++11/c++11-nullptr-strongly-typed-enum-class.html) which properly scopes the enum within the name of the class to avoid conflicts with libraries that use the same name. I think this is a much cleaner solution than prefacing the name of every value with a namespace.

**Comment by gorkacortazar** [comment]
For sure its a cleaner solution, I will test it and comment in a few hours...
