### ISSUE TITLE
ofxDatGuiSliderEvent spitting twice

### ISSUE THREAD

**Issue by aferriss** [braitsch/ofxDatGui#63]
The slider events seem to be getting called twice per click. 

ofApp.h

```
ofxDatGui* gui;
ofxDatGuiSlider* guiMaxW;
ofxDatGuiSlider* guiMaxH;
void onSliderEvent(ofxDatGuiSliderEvent e);
```

ofApp.cpp

```
void ofApp::setup(){
    gui = new ofxDatGui( ofxDatGuiAnchor::TOP_LEFT );
    guiMaxW = gui->addSlider("Max Width", 1,200,64);
    guiMaxH = gui->addSlider("Max Height", 1, 200,32);
    gui->onSliderEvent(this, &ofApp::onSliderEvent);
}

void ofApp::onSliderEvent(ofxDatGuiSliderEvent e){
    if(e.target->is("Max Width")){
        cout<<ofToString(e.value)<<endl;
    }else if (e.target->is("Max Height")){
        cout<<ofToString(e.value)<<endl;
    }
}
```

If I click my slider it will print the value that the slider has when I first clicked, and then the value that I moved the slider to. Am I right in thinking it should only print the latter? Did I set something up incorrectly?

Edit: I should clarify that this only happens when clicking on the bar of the slider itself. Setting the numerical value in the box only triggers the event once, as does sliding the mouse side to side after an initial click. That initial click still triggers two events though.

I'm wondering if mousePressed and mouseDragged are both sending events?

**Comment by braitsch** [comment]
Hi, this is a bug. The event should only dispatch when the value of the slider has changed, e.g. ```onMouseDragged``` or ```onInputChanged```. I'll push up a fix in a few minutes. Thanks for reporting this!
