### ISSUE TITLE
Remove an element during run time.

### ISSUE THREAD

**Issue by faaip** [braitsch/ofxDatGui#64]
I'm making a program where it'd be useful to replace a slider with a label after a button has been pressed. I got the event listener up and running, but I cannot seem to figure out how to remove an element from the GUI during runtime.

Thank you so much,
Fred

**Comment by braitsch** [comment]
While it's not currently possible to remove or destroy a component at runtime you can achieve what your after by simply toggling your slider's and button's visibility.

````
mySlider = gui->addSlider("my slider", 0, 100);
myLabel = gui->addLabel("slider hidden");
myLabel->setVisible(false);
myButton = gui->addButton("my button");
gui->onButtonEvent(this, &ofApp::onButtonEvent);

void ofApp::onButtonEvent(ofxDatGuiButtonEvent e)
{
    if (e.target == myButton){
        myLabel->setVisible(true);
        mySlider->setVisible(false);
    }
}
````

**Comment by faaip** [comment]
Thanks for the quick reply. 

In my event listener I have the following code:


void GUI::onButtonEvent(ofxDatGuiButtonEvent e){
    if (e.target->is("Start!")){
        cout << "Start button was clicked!" << endl;
        populationSizeSlider->setVisible(false);
        populationSizeLabel->setVisible(true);
    }
}

But when I press the button, I get the following exception:

![screen shot 2016-04-13 at 18 45 16](https://cloud.githubusercontent.com/assets/8987733/14501686/f2c796d2-01a7-11e6-8ba7-0b57c45e3cd2.png)

Could this because I have the GUI in a separate class? The whole code, which is still in its infancy, can be seen here : https://github.com/SaraFred/Bachelor

Thanks

**Comment by braitsch** [comment]
Just taking a quick glance at your code I can see that your gui is going out of scope within your ``setupGui`` method.

````
void ofApp::setupGui(){
    ofxDatGui* gui = new ofxDatGui( ofxDatGuiAnchor::TOP_LEFT );
````

It should be declared within a header file. Take a look at one of the many examples in the repository for guidance.

**Comment by faaip** [comment]
That did it, thank you so much

**Comment by braitsch** [comment]
👍

**Comment by kelvynmarte** [comment]
Is there any update on this? Is it still not possible to remove an element e.g. from an dropdown …

**Comment by mattfelsen** [comment]
@kelvynmarte I don't believe anything has changed, but it is pretty easy to add a function that lets you remove a component. Here's something I added to my fork to let me remove items. Note that I don't mean remove options from a dropdown, though you could do something like remove your dropdown, create one with new options, and then add that.

https://github.com/mattfelsen/ofxDatGui/commit/0b2403114d34cd3563b5b2b9f68d23ac094c25fd

I used this to build a dynamic UI that would add some checkboxes & sliders based on the number of serial ports detected after hitting a button to scan for them and it worked well for me.
