### ISSUE TITLE
Custom Fonts

### ISSUE THREAD

**Issue by transat** [braitsch/ofxDatGui#67]
Is there a way to include a custom font as part of a theme?

**Comment by braitsch** [comment]
You can change any value that is exposed in [ofxDatGuiTheme](https://github.com/braitsch/ofxDatGui/blob/master/src/themes/ofxDatGuiTheme.h#l217) which includes fonts near the end of the file. The best practice is to create a custom theme that extends ofxDatGuiTheme and define your settings there. This will allow you to switch between any number of themes using ``gui->setTheme()`` or ``component->setTheme()``. Take a look at the [included custom themes for an example](https://github.com/braitsch/ofxDatGui/blob/master/src/themes/ofxDatGuiThemes.h) of how to create your own theme.
