### ISSUE TITLE
Rotate icon.dropdown by 180 degrees when folder is expanded

### ISSUE THREAD

**Issue by transat** [braitsch/ofxDatGui#68]
I've got the arrow pointing up when a folder is expanded and I think it works better that way on folder-heavy UIs. I'd send a pull request but my hack involves a new image rather than a straightforward rotation (I'm just a beginner with C++). Any chance to add this as enhancement?

**Comment by braitsch** [comment]
The icons are currently shared_ptrs (for performance reasons) so changing the visual state of one will affect all components that use that texture. This is a good idea though and would be a nice enhancement but will require adjustments to how the underlying textures are mapped to the UI.

**Comment by braitsch** [comment]
Thanks for your questions and feature requests btw. If you're interested in the project it would be appreciated if you starred the repository.

**Comment by transat** [comment]
Of course. Thought I had already! Thanks for what you've done so far.

**Comment by braitsch** [comment]
Cool, glad you're enjoying the project!

**Comment by transat** [comment]
Confirming @mattfelsen 's PR is working great.
