### ISSUE TITLE
button->setVisibility( false ) hides button but is still active

### ISSUE THREAD

**Issue by dhenrie0208** [braitsch/ofxDatGui#73]
I'm trying to evaluate the functionality of the ->setVisibility(...) method of the components.

I have two buttons on top of each other:

```
[ Click! ]      ( ofxDatGuiButton* gui_click    = gui->addButton( "Click!" );    )
[ Clickety! ]   ( ofxDatGuiButton* gui_clickety = gui->addButton( "Clickety!" ); )
```

My onButtonEvent code has the following:

```
void ofApp::onButtonEvent( ofxDatGuiButtonEvent e )
{
  printf( "button %s pressed", e.target->getLabel().c_str() );

  if( e.target == gui_click )
  {
    printf( "..." );
  }
  else if( e.target == gui_clickety )
  {
    printf( "?" );
    gui_click->setVisible( !gui_click->getVisible() );
  }

  printf( "\n" );
}
```

When I press the 2nd button ("Clickety!"), the 1st one ("Click!") becomes hidden, and the message "button CLICKETY! pressed?" is printed. Subsequent button presses on the only remaining button ("Clickety!") trigger the events associated with the now non-visible button ("Click!"), printing "button CLICK! pressed...".

In other words, e.target is still returning the pointer for the original 1st button ("Click!") and not for the new 1st button ("Clickety!").

**I'm guessing that the pointer e.target is coming from an array or vector of pointers from the ofxDatGui gui the buttons are a part of, but that the code returning the GUI component pointer is not taking into account the ->getVisible() state of the component. Could this be investigated?**

Also, I added a 3rd button, and when I click on the 2nd button, the 1st one gets hidden, but the pointer to the 3rd button is still good:

```
[ Click! ]
[ Clickety! ]   ( clicking returns the correct pointer and correctly hides the "Click!" button )
[ Etyetyety! ]

becomes:

[ Clickety! ]    ( clicking returns the pointer of the "Click!" button )
[ Etyetyety! ]   ( correctly returns the pointer of the "Etyetyety!" button )
```

Further combinations of GUI components hiding each other should be tested to evaluate this bug.

**Comment by nebgnahz** [comment]
I also ran into this issue; and the minimal reproducible I have is to use the example-AllComponentsGui. The `onButtonEvent` is updated such that if the `CLICK` button is pressed, the button will be invisible. After doing this, `toggle fullscreen` checkbox no longer functions to toggle fullscreen.

Below is the code:
```
void ofApp::onButtonEvent(ofxDatGuiButtonEvent e)
{
    if (e.target->is("toggle fullscreen")) { toggleFullscreen(); return; }
    cout << "onButtonEvent: " << e.target->getLabel() << " " << e.target->getEnabled() << endl;
    e.target->setVisible(false);
}
```

**Comment by braitsch** [comment]
Hello, just pushed up a batch that should resolve this. Indeed mouse events were still being processed even if the component was set to invisible, thanks for the bug report. @dhenrie0208 As for stacking buttons there currently is no mechanism to prevent mouse events from propagating through one component into another.
