### ISSUE TITLE
Easy font sizing

### ISSUE THREAD

**Issue by mruegenberg** [braitsch/ofxDatGui#75]
Right now, the standard UI font is extremely small. My eyes are not particularly bad and yet I almost can't read some GUI items.

The attempt to create a new theme and set its `font.size` to a larger value doesn't do anything at all.

**Comment by braitsch** [comment]
The following is how you set a custom font size. You can edit any of the stock themes and cycle through them in the ``AllComponentsGui`` example by pressing the space bar.

````
class ofxDatGuiCustomFontSize : public ofxDatGuiTheme{

    public:
    
        ofxDatGuiCustomFontSize()
        {
            font.size = 20;
            init();
        }
};
````

**Comment by mruegenberg** [comment]
Great, that seems to work :)

Just a note for reference: when adding folders, `setTheme` needs to be called on the folder as well, after all components were added.

**Comment by jsteele13** [comment]
This changes the size successfully for me, but for some reason it also causes the input field to show up on top of the label. Any ideas why that might be? 

To set the font size of my gui I called the following with exact same code as above.
`panel->setTheme(new ofxDatGuiCustomFontSize());`
