### ISSUE TITLE
Fixed components width when working on a high dpi screen

### ISSUE THREAD

**Issue by razvanilin** [braitsch/ofxDatGui#77]
Hi there, I was testing my application on a surface pro 4 and I discovered some issues with the themes. I created my own custom theme and I realised that if I apply it to my gui, it applies a fix width to the components (540 see below).

```
if (ofxDatGuiIsRetina()){
                font.size *= 2;
                stripe.width *= 2;
                //layout.width = 540;
                layout.height *= 2;
                layout.padding *= 2;
                layout.vMargin *= 2;
                layout.iconSize *= 2;
                //layout.labelWidth = 190;
                layout.graph.height *=2;
                layout.pad2d.height *=2;
                layout.pad2d.ballSize *=2;
                layout.pad2d.lineWeight *=2;
                layout.matrix.height *=2;
                layout.matrix.buttonSize = 47;
                layout.textInput.highlightPadding *= 2;
            }
```
To my understanding the commented lines above overwrite the settings applied in the custom theme which is not that favourable. Why the fixed values anyway?

**Comment by braitsch** [comment]
Hi, you're absolutely right. Those hardcoded values were holdovers from when I was first working on adding retina support and I just removed them and updated the base non-retina values that are doubled when retina is enabled. Thanks for bringing this to my attention.
