### ISSUE TITLE
Problems in switch between the retina screen and the no retina screen

### ISSUE THREAD

**Issue by logic1988** [braitsch/ofxDatGui#79]
I am using openframeworks 0.9.0 and ofxDatGui v1.00 in Mac OSX 10.11.
There are two display screen, the one is retina screen and other is not.
And I set the option "High Resolution Capable" to "YES" in xcode. 
It works fine on a single screen, but when I drag the window to another screen, there is a problem.
The size and position of GUI are not correct, and does not match the mouse position.
Is there any way to solve this problem?

**Comment by braitsch** [comment]
I don't believe oF supports both retina & non-retina displays within the same app. Consider asking about this on the [OpenFrameworks forum](https://forum.openframeworks.cc/).

**Comment by kritzikratzi** [comment]
@logic1988  it's an open issue in OF: https://github.com/openframeworks/openFrameworks/issues/4703
