### ISSUE TITLE
Pixelated Font/High Resolution Retina Xcode build settings 

### ISSUE THREAD

**Issue by adielfernandez** [braitsch/ofxDatGui#80]
Hey Braitsch,

Beautiful addon, seriously. Just a question about some Xcode build settings for retina. When running the All_components example the gui looks great with sharp text. However when building my own example, the gui text looks pixelated and the console log indicates the font loaded "@ pt size 6". 

I changed the settings in my xcode build (in openFrameworks-Info.plist) to allow High Resolution Capable = YES, which fixes the pixelation with the console indicating "@ pt size 12" but now my app window is drawing 1/4 the size. Can you share what XCode build settings allow the font to load correctly but still maintain the proper scaling of the app to display on Retina? 

I'm sure other people have come across this issue as well so it might be worth adding a note in the readme. Thanks!

**Comment by braitsch** [comment]
OpenFrameworks does not currently scale the window based on the application's resolution and instead relies on the user to account for this manually. [This however may change in v10.0](https://github.com/openframeworks/openFrameworks/issues/4789)

**Comment by adielfernandez** [comment]
Ahh, I see. Then is there any other way to get non-pixelated text/radio buttons/icons in the gui without enabling the High Resolution Capable?

**Comment by braitsch** [comment]
If you're on a high resolution screen you should set "High Resolution Capable" to YES and then increase the size of your window with ``ofSetWindowSize(width, height)``. Alternatively you can change the size of the gui components & icons by editing one of the themes but that will never look as good as simply enabling high resolution capable in your app.

**Comment by adielfernandez** [comment]
Right, I was trying to get the gui looking as good as you intended it without having to double the window dimensions (and suffering the performance loss from 4x the pixels). Either way, it still looks great. 

Side note, any plans to build in settings saving/loading in the future (xml or otherwise)? 

Thanks again!
