### ISSUE TITLE
ofxDatGui class destructor

### ISSUE THREAD

**Issue by techtim** [braitsch/ofxDatGui#81]
Why there aint no detors? Static mGuis vector never clears , is that a design decision? 
What if I have class instance that creates gui, then it destructs and what happens to mGuis vector ?

**Comment by techtim** [comment]
At least something like this would be nice.
ofxDatGui::~ofxDatGui() {
    mGuis.erase(std::remove(mGuis.begin(), mGuis.end(), this), mGuis.end());
}

Btw love your addon, thanks for your work

**Comment by pierrep** [comment]
I'd like to see some more clean-up too.  Currently ofxDatGuiFolders are also not cleaning up after themselves once you've added some components to them.
