### ISSUE TITLE
doesn't 'layout.upperCaseLabels = false;' affect in subclass of ofxDatGuiTheme?

### ISSUE THREAD

**Issue by 2bbb** [braitsch/ofxDatGui#82]
hi.

i use this addon, and i wanna customize theme.
and i write like this:

```cpp
class ofxDatGuiThemeCustom : public ofxDatGuiTheme {
public:
    ofxDatGuiThemeCustom()
    {
...
        layout.upperCaseLabels = false;
...
        init();
    }
};

void ofApp::setup() {
        gui = new ofxDatGui(ofxDatGuiAnchor::TOP_RIGHT);
        gui->setTheme(new ofxDatGuiThemeCustom);
        
        gui->addHeader("foo");
...
}
```

but, labels are shown with uppercase yet.

i added the logging like this:

```cpp
void ofxDatGuiComponent::setLabel(string label)
{
    ofLogNotice("before") << label;
    if (mLabel.forceUpperCase) label = ofToUpper(label);
    ofLogNotice("after") << label;
    mLabel.text = label;
    mLabel.rect = mFont->rect(mLabel.text);
    positionLabel();
}
```

and i got:

```
[notice ] before: foo
[notice ] after: FOO
[notice ] before: FOO
[notice ] after: FOO
```
mmmm...

have i wrote the wrong code? or bug?

best regards.

**Comment by braitsch** [comment]
Are you working with the latest on master? I just pushed up a [commit](https://github.com/braitsch/ofxDatGui/commit/d1ec7af9bb2cfcc6e420bec92c2e85b98717d370) a few days ago that changes how themes are applied to labels and text inputs.

**Comment by 2bbb** [comment]
@braitsch 
oh yeah... sorry!!
i will check it!!

**Comment by 2bbb** [comment]
@braitsch 
really sorry, it's just as you said.
thanks!!
