### ISSUE TITLE
doesn't ofxDatGuiMatrixButton::setSelected change appearance itself?

### ISSUE THREAD

**Issue by 2bbb** [braitsch/ofxDatGui#83]
now, i write a code like:

```cpp
std::vector<int> values;

void setup() {
  values = {1, 0, 1, 0};
  gui->addMatrix("foo", 4);
  for(auto i = 0; i < 4; i++) {
    gui->getChildAt(i)->setSelected(values[i] == 1);
  }
}
```

but, matrix all of color of buttons are same to `color.matrix.normal.button`.
and i added a little code into `setSelected` like:

```cpp
        void setSelected(bool selected)
        {
            mSelected = selected;
            
            if (mSelected){
                mBkgdColor = colors.selected.button;
                mLabelColor = colors.selected.label;
            } else {
                mBkgdColor = colors.normal.button;
                mLabelColor = colors.normal.label;
            }
        }
```

but it is still same behavior.

could i change appearance programmatically?

**Comment by braitsch** [comment]
Not sure I understand your question but perhaps you're asking if the matrix can function as a radio group where only one button can be selected at a time? If that is the case set radio mode to true.

    gui->addMatrix("matrix", 21)->setRadioMode(true);

**Comment by braitsch** [comment]
If you're trying to programmatically select the buttons you need a reference to the matrix.

````
gui->addMatrix("foo", 4);
for(auto i = 0; i < 4; i++) {
// this line is returning four different components in your gui, not the buttons in the matrix
    gui->getChildAt(i)->setSelected(values[i] == 1);
// you can retrieve the matrix via:
    gui->getMatrix("foo")->getChildAt(i)->setSelected(values[i] == 1);
}
````

**Comment by 2bbb** [comment]
@braitsch 
thanks for reply.

omg...
sorry, my example is wrong...

correct code is:

```
std::vector<int> values;

void setup() {
  values = {1, 0, 1, 0};
  auto matrix = gui->addMatrix("foo", 4);
  for(auto i = 0; i < 4; i++) {
    matrix->getChildAt(i)->setSelected(values[i] == 1);
  }
}
```

and my question is "why doesn't change appearance of button after setSelected(true/false)?"
i expect behavior that appearance will change as similar to behavior after click on button.
it is not related to radio mode or not.
(sorry my english is not good...)

**Comment by braitsch** [comment]
Hi, I just tested your code in the AllComponentsGui example and the buttons are changing state just fine.   This is what I see when I run your code. The first and third button are selected just as if they were clicked with the mouse.
<img width="331" alt="screen shot 2016-07-07 at 3 22 05 pm" src="https://cloud.githubusercontent.com/assets/144289/16671866/ff9d39a6-4456-11e6-97d3-37c5c236cce8.png">

**Comment by 2bbb** [comment]
@braitsch 
oh... really...? mmmm...
okay, i will check my code again.

thanks.

**Comment by 2bbb** [comment]
@braitsch 
okay, i found cause of a problem.
cause is setTheme (setTemplate).

at AllComponentGui example, erase comment out on line 12:
```
    gui->setTemplate(new ofxDatGuiExampleCustomTemplate());
```
then reproduce the problem.

i don't know why it happen, but maybe, is this simple bug?

**Comment by braitsch** [comment]
````
gui->setTemplate(new ofxDatGuiExampleCustomTemplate());
````
does not exist in the AllComponentGui example.

**Comment by 2bbb** [comment]
@braitsch 
sorry. it is my mistake. (I was watching a another directory is download by zip)

but problem is still there.
test on newest AllComponentGui (in d1ec7af9bb2cfcc6e420bec92c2e85b98717d370)

add line:
```
// a button matrix //
    gui->addMatrix("matrix", 21, true);
    gui->getMatrix("matrix")->getChildAt(0)->setSelected(true); // added
```

when start up, it is correct.

<img width="204" alt="ss 2016-07-11 18 07 35" src="https://cloud.githubusercontent.com/assets/200899/16725554/bafcaf86-4792-11e6-8ce5-7be18c36d592.png">

but after press space key to change theme, select states be incorrect.

<img width="279" alt="ss 2016-07-11 18 07 48" src="https://cloud.githubusercontent.com/assets/200899/16725569/ca51302e-4792-11e6-9915-400186263cda.png">

**Comment by 2bbb** [comment]
@braitsch 
very sorry, it is my mistake. i was check on another directory (it was download with zip)

but maybe problem is still there.

i tested AllComponentGui on newest master branch (hash is 6b86ea187a9d313c2a2f635cf8093a67e7c90a35)
select state of matrix button will be reset after changing theme with pressing space key.
is this specification?
