### ISSUE TITLE
Font rendering switches color on lowest rightmost pixel

### ISSUE THREAD

**Issue by elblaus** [braitsch/ofxDatGui#9]
I have an issue with the font rendering in the gui. 

![screen shot 2015-10-15 at 18 59 06](https://cloud.githubusercontent.com/assets/6004983/10521226/e8b9f5f8-736e-11e5-90d3-01987c85b57e.png)

Look at the N in ON in the picture, you can clearly see the lowest rightmost pixel missing. You can also see that in ANIMATION, that is highlighted by mouseover, the pixels are somehow there but the wrong color. 

The issue can also be seen in the demo videos: http://braitsch.github.io/ofxDatGui/gallery.html . For instance, in https://www.youtube.com/watch?v=IrmABSyabng , the lowest horizontal bar on the E looks short, the N have a similar problem as my screenshot, the H looks odd, and there seem to be some other issues as well. 

I am at a loss on how to move forward with this. Any suggestions?

I should add that I'm on OSX 10.10.3 with oF 0.9.0 RC1 with ofxDatGUI as the only addon.

**Comment by braitsch** [comment]
This is either an issue with freetype, or oF itself as I'm just calling draw on the ofTrueTypeFont instance. I agree though it is particularly noticeable on non-retina displays. Have you tried a different font file?

**Comment by elblaus** [comment]
Well, if you look at the image below you'll see that I draw a string using an ofTrueTypeFont with the same ttf-file and size as the gui. But the lowest rightmost pixel is set to black in the gui but not in the text rendered with the drawString-command. Also compare the A in ANIMATION with the lower LINEAR SINE. The N looks weird in both places though. 

![screen shot 2015-10-16 at 00 42 46](https://cloud.githubusercontent.com/assets/6004983/10529580/86912e24-739f-11e5-83a3-4286d980306d.png)

I tried many different font-files, the issue becomes less noticeable with a larger font size (since less of the letter is missing), but it is still there.

**Comment by braitsch** [comment]
Closing this as it is not something I can resolve.

**Comment by braitsch** [comment]
This appears to have been an [oF issue that was resolved in 0.9.](https://forum.openframeworks.cc/t/dark-pixel-at-oftruetypefont-drawstring/22178)
