### ISSUE TITLE
Semantic issues shown when using clang

### ISSUE THREAD

**Issue by hamoid** [braitsch/ofxDatGui#93]
Hi, I do get many Semantic issues (shown as errors, even if the program runs fine).

I shared screenshots in the OF forum: https://forum.openframeworks.cc/t/semantic-issues-with-ofxdatgui-on-qtcreator/24371

Are those issues of my code, or of ofxDatGui?

**Comment by braitsch** [comment]
Those warnings look tied to your compiler which unfortunately I can't help you with as I don't have much experience with QtCreator.
